### ISSUE TITLE
Can't import Leiningen projects

### ISSUE THREAD

**Issue by atroche** [cursiveclojure/cursive#1008]
I was using IntelliJ 14 and the latest Cursive, and when I tried to import a project (whether an old one, or one just initialised with `lein new`), I'd see this:

![import_project_and_welcome_to_intellij_idea_and_new_issue_ _cursiveclojure_cursive](https://cloud.githubusercontent.com/assets/29839/9159584/b820cb44-3f6e-11e5-81d3-eba297f687a5.jpg)

If I just tried opening the `project.clj`, I'd see:

![project_clj_-_blah_-____code_clj_blah__-_intellij_idea__community_edition__ic-142_3728_3_and_cursive__working_with_leiningen](https://cloud.githubusercontent.com/assets/29839/9159577/76677f9a-3f6e-11e5-9e63-23bbb4aeb554.jpg)

and then

![project_clj_-_blah_-____code_clj_blah__-_intellij_idea__community_edition__ic-142_3728_3_and_cursive__working_with_leiningen](https://cloud.githubusercontent.com/assets/29839/9159576/60fcb6e8-3f6e-11e5-8929-51935548ddfa.jpg)

I installed IntelliJ 15 CE, and didn't import any new settings. I installed the latest Cursive. And now I'm still having the same problem.

What should I try next?

**Comment by danielcompton** [comment]
Try moving your `~/.lein/profiles.clj` file somewhere else and rerunning it. You'll need to close IntelliJ completely first as Leiningen caches the `profiles.clj` file.

**Comment by cursiveclojure** [comment]
Do you see anything in your log? You can see it with *Help&rarr;Show log in Finder/Explorer*.

**Comment by atroche** [comment]
@danielcompton it ran when I moved profiles.clj =) thanks for that.

@cursiveclojure I couldn't get anything useful out of it:

```
2015-08-10 14:51:11,136 [ 963188]  ERROR - ursive.leiningen.LeiningenUtil - No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil 
java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:566)
	at clojure.java.io$fn__9115$G__9091__9122.invoke(io.clj:69)
	at clojure.java.io$reader.doInvoke(io.clj:102)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at leiningen.core.main$leiningen_version.invoke(main.clj:313)
	at clojure.lang.Var.invoke(Var.java:375)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1130)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1150)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1150)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.LispReader.read(LispReader.java:185)
	at clojure.lang.RT.readString(RT.java:1821)
	at clojure.lang.RT.readString(RT.java:1816)
	at clojure.core$read_string.invoke(core.clj:3663)
	at leiningen.core.utils$read_file.invoke(utils.clj:30)
	at leiningen.core.user$fn__11011.invoke(user.clj:67)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$memoize$fn__5479.doInvoke(core.clj:6082)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at leiningen.core.user$fn__11014.invoke(user.clj:85)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$memoize$fn__5479.doInvoke(core.clj:6082)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at leiningen.core.project$read_profiles.invoke(project.clj:654)
	at leiningen.core.project$project_with_profiles.invoke(project.clj:798)
	at cursive.leiningen$read_project.invoke(leiningen.clj:79)
	at cursive.leiningen$load_project.invoke(leiningen.clj:86)
	at clojure.lang.Var.invoke(Var.java:379)
	at cursive.leiningen.utils.Interop.loadProject(Interop.java:22)
	at cursive.leiningen.project.LeiningenProject.reload(LeiningenProject.java:38)
	at cursive.leiningen.project.LeiningenProject.<init>(LeiningenProject.java:34)
	at cursive.leiningen.project.LeiningenProject.create(LeiningenProject.java:29)
	at cursive.leiningen.project.LeiningenProjectsManager.importLeiningenProjects(LeiningenProjectsManager.java:114)
	at cursive.notifications.LeiningenProjectNotificationProvider$3.run(LeiningenProjectNotificationProvider.java:69)
	at com.intellij.ui.EditorNotificationPanel$2.hyperlinkActivated(EditorNotificationPanel.java:93)
	at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:28)
	at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:188)
	at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:121)
	at java.awt.Component.processEvent(Component.java:6308)
	at java.awt.Container.processEvent(Container.java:2235)
	at java.awt.Component.dispatchEventImpl(Component.java:4899)
	at java.awt.Container.dispatchEventImpl(Container.java:2293)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4897)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4529)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4461)
	at java.awt.Container.dispatchEventImpl(Container.java:2279)
	at java.awt.Window.dispatchEventImpl(Window.java:2750)
	at java.awt.Component.dispatchEvent(Component.java:4721)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:643)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:378)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I suppose I'll try removing bits and pieces from my profiles.clj until it works…

**Comment by cursiveclojure** [comment]
The issue is that you have a call to `leiningen-version` in your `profiles.clj` somewhere. See #968 for another example.

**Comment by atroche** [comment]
Aha, and this is a problem because Cursive is evaluating `~/.lein/profiles.clj` without having access to `leiningen.core.main`? Thanks for your help!

**Comment by cursiveclojure** [comment]
To be honest, I haven't investigated this much - my stock response so far has been "don't do that". If you really need that function I can try to figure out why it's not working.

**Comment by atroche** [comment]
Not at all =) I'll close the issue.

**Comment by danielcompton** [comment]
It could be good to add this info to the troubleshooting at: https://cursiveclojure.com/userguide/support.html, and possibly making a separate troubleshooting section. You might also get good results adding a CONTRIBUTING.md document to this repo with known/common issues. This will show to people before they create an issue and may save some support tickets.
