### ISSUE TITLE
Can't open Leiningen project

### ISSUE THREAD

**Issue by jstaffans** [cursiveclojure/cursive#1030]
Trying to open a basic project created with `lein new myapp` with Cursive 0.1.60 does not work, the logs show this error:

```
2015-08-21 14:19:09,604 [ 349016]  ERROR - llij.ide.plugins.PluginManager - No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil 
java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:566)
	at clojure.java.io$fn__9115$G__9091__9122.invoke(io.clj:69)
	at clojure.java.io$reader.doInvoke(io.clj:102)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at leiningen.core.main$leiningen_version.invoke(main.clj:313)
	at clojure.lang.Var.invoke(Var.java:375)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1130)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1150)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1150)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.LispReader.read(LispReader.java:185)
	at clojure.lang.RT.readString(RT.java:1821)
	at clojure.lang.RT.readString(RT.java:1816)
	at clojure.core$read_string.invoke(core.clj:3663)
	at leiningen.core.utils$read_file.invoke(utils.clj:30)
	at leiningen.core.user$fn__11013.invoke(user.clj:67)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$memoize$fn__5479.doInvoke(core.clj:6082)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at leiningen.core.user$fn__11016.invoke(user.clj:85)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$memoize$fn__5479.doInvoke(core.clj:6082)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at leiningen.core.project$read_profiles.invoke(project.clj:654)
	at leiningen.core.project$project_with_profiles.invoke(project.clj:798)
	at cursive.leiningen$read_project.invoke(leiningen.clj:79)
	at cursive.leiningen$load_project.invoke(leiningen.clj:86)
	at clojure.lang.Var.invoke(Var.java:379)
	at cursive.leiningen.utils.Interop.loadProject(Interop.java:22)
	at cursive.leiningen.project.LeiningenProject.reload(LeiningenProject.java:39)
	at cursive.leiningen.project.LeiningenProject.<init>(LeiningenProject.java:35)
	at cursive.leiningen.project.LeiningenProject.create(LeiningenProject.java:30)
	at cursive.leiningen.project.LeiningenProjectOpenProcessor.doQuickImport(LeiningenProjectOpenProcessor.java:35)
	at com.intellij.projectImport.ProjectOpenProcessorBase.doOpenProject(ProjectOpenProcessorBase.java:132)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:124)
	at com.intellij.ide.actions.OpenFileAction.doOpenFile(OpenFileAction.java:88)
	at com.intellij.ide.actions.OpenFileAction.access$000(OpenFileAction.java:50)
	at com.intellij.ide.actions.OpenFileAction$1.consume(OpenFileAction.java:68)
	at com.intellij.ide.actions.OpenFileAction$1.consume(OpenFileAction.java:58)
	at com.intellij.ui.mac.MacFileChooserDialogImpl$3$2.run(MacFileChooserDialogImpl.java:153)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2015-08-21 14:19:09,607 [ 349019]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 14.1.4  Build #IC-141.1532.4 
2015-08-21 14:19:09,607 [ 349019]  ERROR - llij.ide.plugins.PluginManager - JDK: 1.6.0_65 
2015-08-21 14:19:09,607 [ 349019]  ERROR - llij.ide.plugins.PluginManager - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-08-21 14:19:09,607 [ 349019]  ERROR - llij.ide.plugins.PluginManager - Vendor: Apple Inc. 
2015-08-21 14:19:09,607 [ 349019]  ERROR - llij.ide.plugins.PluginManager - OS: Mac OS X 
2015-08-21 14:19:09,607 [ 349019]  ERROR - llij.ide.plugins.PluginManager - Last Action: OpenFile
```

0.1.59 showed the same behavior.

**Comment by cursiveclojure** [comment]
I can't reproduce this, I suspect you have something in your lein profiles which is causing a call to `leiningen-version` to be inserted into your project somewhere. Is that possible?

**Comment by jstaffans** [comment]
Yep, duplicate of https://github.com/cursiveclojure/cursive/issues/968
