### ISSUE TITLE
Plugin fails to initialize with IllegalAccessError

### ISSUE THREAD

**Issue by moskvax** [cursiveclojure/cursive#1147]
I'm getting the following error on startup, using 0.1.70 with IDEA 15. La Clojure is disabled.

```
Plugin 'com.cursiveclojure.cursive' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.IllegalAccessError: tried to access method clojure.lang.RT.classForNameNonLoading(Ljava/lang/String;)Ljava/lang/Class; from class cursive.repl.ide$loading__5340__auto____10729
    at cursive.repl.ide$loading__5340__auto____10729.invoke(ide.clj:1)
    at cursive.repl.ide__init.load(Unknown Source)
    at cursive.repl.ide__init.<clinit>(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at clojure.lang.RT.loadClassForName(RT.java:2098)
    at clojure.lang.RT.load(RT.java:430)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5496)
    at clojure.lang.RestFn.invoke(RestFn.java:3894)
    at cursive.initialise$loading__5340__auto____10727.invoke(initialise.clj:1)
    at cursive.initialise__init.load(Unknown Source)
    at cursive.initialise__init.<clinit>(Unknown Source)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:348)
    at clojure.lang.RT.loadClassForName(RT.java:2098)
    at clojure.lang.RT.load(RT.java:430)
    at clojure.lang.RT.load(RT.java:411)
    at clojure.core$load$fn__5018.invoke(core.clj:5530)
    at clojure.core$load.doInvoke(core.clj:5529)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.core$load_one.invoke(core.clj:5336)
    at clojure.core$load_lib$fn__4967.invoke(core.clj:5375)
    at clojure.core$load_lib.doInvoke(core.clj:5374)
    at clojure.lang.RestFn.applyTo(RestFn.java:142)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$load_libs.doInvoke(core.clj:5413)
    at clojure.lang.RestFn.applyTo(RestFn.java:137)
    at clojure.core$apply.invoke(core.clj:619)
    at clojure.core$require.doInvoke(core.clj:5496)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:415)
    at cursive.config.InitComponent.initClojure(InitComponent.java:112)
    at cursive.config.InitComponent.initComponent(InitComponent.java:63)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:123)
    at com.intellij.openapi.application.impl.ApplicationImpl.access$801(ApplicationImpl.java:90)
    at com.intellij.openapi.application.impl.ApplicationImpl$12.run(ApplicationImpl.java:496)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:505)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:107)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:454)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:446)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:194)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:52)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by cursiveclojure** [comment]
If you have La Clojure installed, you'll need to completely uninstall it. For dull historical reasons there's a conflict between the two. This error means that somehow Cursive is picking up an old version of Clojure, and the only way I can see that being possible is if it's getting the La Clojure one somehow, although I can't think how. It's possible that you might need to uninstall both and then reinstall Cursive.

**Comment by cold-gin** [comment]
I am receiving this exception also with Intellij 15 EAP 143.747.6:

IllegalAccessError: tried to access class com.intellij.execution.impl.MyDiffContainer from class cursive.runner.console.ConsoleViewImpl
IllegalAccessError: com/intellij/execution/impl/MyDiffContainer

I uninstalled La Clojure, and I also re-installed Cursive. Still get the error when running any of the tasks from the Leiningen panel. I created the project through "Create New Project" after the Cursive plugin was re-installed.

**Comment by cursiveclojure** [comment]
@cold-gin Your exception is different, and is fixed in #1167.

**Comment by cursiveclojure** [comment]
@moskvax Could you reproduce the problem, and then mail me your whole log (*Help->Show log in Finder/Explorer*) to cursive@cursiveclojure.com?

**Comment by moskvax** [comment]
@cursiveclojure This error would always happen to me on my laptop, but never on my desktop with the same plugin and IntelliJ versions, so I was pretty confused about how to reproduce it. I also never actually had the La Clojure plugin installed on my laptop, according to the plugins manager.

Yesterday I looked into this issue a bit more, and noticed after uninstalling Cursive there were still jars in the `~/.IdeaIC15/config/plugins/clojure-plugin` directory. After removing the entire directory manually and reinstalling Cursive, the error stopped happening, and Cursive seems to be working fine now.

My best guess is that it's related to having copied my IntelliJ configuration from an old 1.4 configuration, itself probably copied from a 1.3 configuration, with which I may once have tried to use La Clojure. I'll mail you the logs anyway, in case it helps prevent this error in the future.

**Comment by cursiveclojure** [comment]
I'll take a look at the logs to see if I can see anything, but your theory sounds plausible. Thanks for letting me know!
