### ISSUE TITLE
NoSuchElementException when attempting to configure REPL on 0.1.70

### ISSUE THREAD

**Issue by ricardojmendez** [cursiveclojure/cursive#1148]
IntelliJ IDEA 14, Cursive 0.1.70

```
Collection is empty.
java.util.NoSuchElementException: Collection is empty.
	at kotlin.CollectionsKt___CollectionsKt.first(_Collections.kt:197)
	at kotlin.CollectionsKt.first(Unknown Source)
	at cursive.leiningen.run.LeiningenRunConfigurationSettings.resetEditorFrom(LeiningenRunConfigurationSettings.kt:38)
	at cursive.leiningen.run.LeiningenRunConfigurationSettings.resetEditorFrom(LeiningenRunConfigurationSettings.kt:20)
	at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:88)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.resetEditorFrom(ConfigurationSettingsEditor.java:310)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.resetEditorFrom(ConfigurationSettingsEditor.java:294)
	at com.intellij.openapi.options.CompositeSettingsEditor.resetEditorFrom(CompositeSettingsEditor.java:51)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.resetEditorFrom(ConfigurationSettingsEditorWrapper.java:108)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.resetEditorFrom(ConfigurationSettingsEditorWrapper.java:45)
	at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:88)
	at com.intellij.openapi.options.SettingsEditorConfigurable.reset(SettingsEditorConfigurable.java:50)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.reset(SingleConfigurationConfigurable.java:121)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:100)
	at com.intellij.execution.impl.RunConfigurable.a(RunConfigurable.java:374)
	at com.intellij.execution.impl.RunConfigurable.access$600(RunConfigurable.java:76)
	at com.intellij.execution.impl.RunConfigurable$4.valueChanged(RunConfigurable.java:263)
	at javax.swing.JTree.fireValueChanged(JTree.java:2926)
	at javax.swing.JTree$TreeSelectionRedirector.valueChanged(JTree.java:3387)
	at javax.swing.tree.DefaultTreeSelectionModel.fireValueChanged(DefaultTreeSelectionModel.java:635)
	at com.intellij.ui.treeStructure.Tree$MySelectionModel.fireValueChanged(Tree.java:654)
	at javax.swing.tree.DefaultTreeSelectionModel.notifyPathChange(DefaultTreeSelectionModel.java:1093)
	at javax.swing.tree.DefaultTreeSelectionModel.setSelectionPaths(DefaultTreeSelectionModel.java:294)
	at javax.swing.JTree.setSelectionPaths(JTree.java:1646)
	at javax.swing.JTree.setSelectionRows(JTree.java:1728)
	at javax.swing.JTree.setSelectionRow(JTree.java:1703)
	at com.intellij.util.ui.tree.TreeUtil$1.run(TreeUtil.java:523)
	at com.intellij.util.ui.tree.TreeUtil.showAndSelect(TreeUtil.java:574)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:466)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentered(TreeUtil.java:457)
	at com.intellij.util.ui.tree.TreeUtil.showRowCentred(TreeUtil.java:452)
	at com.intellij.util.ui.tree.TreeUtil.selectPath(TreeUtil.java:383)
	at com.intellij.util.ui.tree.TreeUtil.selectInTree(TreeUtil.java:833)
	at com.intellij.util.ui.tree.TreeUtil.selectInTree(TreeUtil.java:821)
	at com.intellij.execution.impl.RunConfigurable$6.run(RunConfigurable.java:320)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:778)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:465)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.execution.actions.EditRunConfigurationsAction.actionPerformed(EditRunConfigurationsAction.java:47)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:746)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by cursiveclojure** [comment]
This looks like your leiningen projects are not added to the project correctly. Can you check that in your lein toolwindow, and add them if they're not there? (right click in project view, add as lein project).

**Comment by ricardojmendez** [comment]
I checked, and it's there. Reverting to 0.1.69 solves the issue.
