### ISSUE TITLE
Indexing error when opening an scala project

### ISSUE THREAD

**Issue by jmgimeno** [cursiveclojure/cursive#1165]
This error occurs when opening a scala project (and similar ones when opening java ones).

This appears in the event log:

```
7:47:45 NoSuchMethodError
        Error while indexing /Applications/IntelliJ IDEA 15.app/Contents/plugins/JavaScriptLanguage/lib/JavaScriptLanguage.jar!/com/intellij/lang/javascript/index/predefined/WebGL.js
        To reindex this file IDEA has to be restarted: org.mozilla.javascript.CompilerEnvirons.setRecoverFromErrors(Z)V
7:47:53 NoSuchMethodError
        Error while indexing /Users/jmgimeno/.ivy2/cache/org.scala-lang/scala-compiler/srcs/scala-compiler-2.10.4-sources.jar!/scala/tools/nsc/doc/html/resource/lib/index.js
        To reindex this file IDEA has to be restarted: org.mozilla.javascript.CompilerEnvirons.setRecoverFromErrors(Z)V
7:47:55 NoSuchMethodError
        Error while indexing /Users/jmgimeno/.ivy2/cache/org.scala-lang/scala-compiler/srcs/scala-compiler-2.10.4-sources.jar!/scala/tools/nsc/doc/html/resource/lib/jquery.js
        To reindex this file IDEA has to be restarted: org.mozilla.javascript.CompilerEnvirons.setRecoverFromErrors(Z)V
7:47:57 NoSuchMethodError
        Error while indexing /Users/jmgimeno/.ivy2/cache/org.scala-lang/scala-compiler/srcs/scala-compiler-2.10.4-sources.jar!/scala/tools/nsc/doc/html/resource/lib/jquery-ui.js
        To reindex this file IDEA has to be restarted: org.mozilla.javascript.CompilerEnvirons.setRecoverFromErrors(Z)V
7:47:58 NoSuchMethodError
        Error while indexing /Users/jmgimeno/.ivy2/cache/org.scala-lang/scala-compiler/srcs/scala-compiler-2.10.4-sources.jar!/scala/tools/nsc/doc/html/resource/lib/raphael-min.js
        To reindex this file IDEA has to be restarted: org.mozilla.javascript.CompilerEnvirons.setRecoverFromErrors(Z)V
7:48:18 NoSuchMethodError
        Error while indexing /Users/jmgimeno/.sbt/boot/scala-2.10.4/lib/scala-compiler.jar!/scala/tools/nsc/doc/html/resource/lib/index.js
        To reindex this file IDEA has to be restarted: org.mozilla.javascript.CompilerEnvirons.setRecoverFromErrors(Z)V

And this is the trace:

Error while indexing /Users/jmgimeno/.sbt/boot/scala-2.10.4/lib/scala-compiler.jar!/scala/tools/nsc/doc/html/resource/lib/index.js
To reindex this file IDEA has to be restarted: org.mozilla.javascript.CompilerEnvirons.setRecoverFromErrors(Z)V
java.lang.NoSuchMethodError: org.mozilla.javascript.CompilerEnvirons.setRecoverFromErrors(Z)V
	at cursive.index.js$parse.invoke(js.clj:22)
	at cursive.index.js$index.invoke(js.clj:154)
	at cursive.index.js$index_javascript.invoke(js.clj:200)
	at clojure.lang.Var.invoke(Var.java:379)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
	at cursive.index.PsiDependentIndexExtension$1.map(PsiDependentIndexExtension.java:65)
	at cursive.index.PsiDependentIndexExtension$1.map(PsiDependentIndexExtension.java:38)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1744)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1671)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1616)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:109)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:225)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:239)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner.a(CacheUpdateRunner.java:125)
	at com.intellij.openapi.project.CacheUpdateRunner.processFiles(CacheUpdateRunner.java:84)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:105)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:99)
	at com.intellij.util.indexing.UnindexedFilesUpdater.performInDumbMode(UnindexedFilesUpdater.java:122)
	at com.intellij.openapi.project.DumbServiceImpl$9.run(DumbServiceImpl.java:480)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:471)
	at com.intellij.openapi.project.DumbServiceImpl.access$1500(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$8.run(DumbServiceImpl.java:444)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)



java.lang.NoSuchMethodError: org.mozilla.javascript.CompilerEnvirons.setRecoverFromErrors(Z)V
	at cursive.index.js$parse.invoke(js.clj:22)
	at cursive.index.js$index.invoke(js.clj:154)
	at cursive.index.js$index_javascript.invoke(js.clj:200)
	at clojure.lang.Var.invoke(Var.java:379)
	at cursive.api.DelayedFn.invoke(DelayedFn.java:31)
	at cursive.index.PsiDependentIndexExtension$1.map(PsiDependentIndexExtension.java:65)
	at cursive.index.PsiDependentIndexExtension$1.map(PsiDependentIndexExtension.java:38)
	at com.intellij.util.indexing.MapReduceIndex.update(MapReduceIndex.java:398)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1744)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1671)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1616)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:109)
	at com.intellij.util.indexing.UnindexedFilesUpdater$2.consume(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$1.run(CacheUpdateRunner.java:225)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1169)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable$2.run(CacheUpdateRunner.java:245)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:239)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.CacheUpdateRunner.a(CacheUpdateRunner.java:125)
	at com.intellij.openapi.project.CacheUpdateRunner.processFiles(CacheUpdateRunner.java:84)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:105)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:99)
	at com.intellij.util.indexing.UnindexedFilesUpdater.performInDumbMode(UnindexedFilesUpdater.java:122)
	at com.intellij.openapi.project.DumbServiceImpl$9.run(DumbServiceImpl.java:480)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:471)
	at com.intellij.openapi.project.DumbServiceImpl.access$1500(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$8.run(DumbServiceImpl.java:444)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

**Comment by cursiveclojure** [comment]
Could you reproduce the problem and then mail your whole log (*Help->Show log in Finder/Explorer*) to cursive@cursiveclojure.com?

**Comment by jmgimeno** [comment]
Here's the log file.

Juan Manuel

2015-11-23 4:11 GMT+01:00 cursiveclojure <notifications@github.com>:

**Comment by cursiveclojure** [comment]
I didn't get an attachment there - this reply came to the issue tracker.

**Comment by jmgimeno** [comment]
Hope now it works.

Juan Manuel

2015-11-23 22:01 GMT+01:00 cursiveclojure <notifications@github.com>:

**Comment by jmgimeno** [comment]
Unfortunately, we don’t support that file type.  Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF.

I'll change extension to txt.

Juan Manuel

[idea.log.txt](https://github.com/cursiveclojure/cursive/files/42476/idea.log.txt)

**Comment by cursiveclojure** [comment]
I sent some instructions for testing with a dev build in the Clojurians Slack channel.

**Comment by cursiveclojure** [comment]
Although I have not managed to reproduce this issue, I've made a change for the next build which I believe should fix it. If the problem persists in the next build feel free to re-open this issue.
