### ISSUE TITLE
Got an exception

### ISSUE THREAD

**Issue by rogergl** [cursiveclojure/cursive#376]
Just got a warning from Intellij that this exception happened 3 times:

cursive.psi.impl.ClLiteralImpl cannot be cast to com.intellij.psi.PsiPolyVariantReference: cursive.psi.impl.ClLiteralImpl cannot be cast to com.intellij.psi.PsiPolyVariantReference
java.lang.ClassCastException: cursive.psi.impl.ClLiteralImpl cannot be cast to com.intellij.psi.PsiPolyVariantReference
	at plugin.resolve$resolve.invoke(resolve.clj:36)
	at plugin.extensions.clojure.core.protocols$find_target_methods.invoke(protocols.clj:131)
	at plugin.extensions.clojure.core.protocols$implementation_locals$fn__3902.invoke(protocols.clj:209)
	at clojure.core.protocols$fn__6022.invoke(protocols.clj:79)
	at clojure.core.protocols$fn__5979$G__5974__5992.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6177)
	at plugin.extensions.clojure.core.protocols$implementation_locals.invoke(protocols.clj:208)
	at plugin.extensions.clojure.core.protocols$reify_locals.invoke(protocols.clj:238)
	at plugin.resolve.lists$list_resolve_symbols$fn__6310.invoke(lists.clj:36)
	at clojure.core$map$fn__4207.invoke(core.clj:2487)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1654)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invoke(core.clj:619)
	at plugin.resolve.lists$list_resolve_symbols.invoke(lists.clj:34)
	at plugin.psi$cached_value$reify__5803.compute(psi.clj:344)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:199)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:81)
	at plugin.psi$cached_value.doInvoke(psi.clj:348)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at plugin.resolve.lists$fn__6314.invoke(lists.clj:42)
	at plugin.resolve$fn__6226$G__6221__6231.invoke(resolve.clj:47)
	at plugin.resolve$resolve_from_symbols.invoke(resolve.clj:191)
	at plugin.resolve.lists$process_list_declarations.invoke(lists.clj:59)
	at clojure.lang.Var.invoke(Var.java:431)
	at cursive.psi.impl.list.ClListBaseImpl.processDeclarations(ClListBaseImpl.java:107)
	at plugin.resolve$process_declarations.invoke(resolve.clj:45)
	at plugin.resolve.symbol.editor$editor_resolver$reify__3015$fn__3059.invoke(editor.clj:267)
	at plugin.resolve.symbol.common$tree_walk.invoke(common.clj:36)
	at plugin.resolve.symbol.editor$editor_resolver$reify__3015.resolve_unqualified(editor.clj:266)
	at plugin.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:87)
	at plugin.resolve.symbol$resolve_symbol.invoke(symbol.clj:110)
	at clojure.lang.Var.invoke(Var.java:419)
	at cursive.psi.impl.symbols.ClSymbolImpl$MyResolver.resolve(ClSymbolImpl.java:133)
	at cursive.psi.impl.symbols.ClSymbolImpl$MyResolver.resolve(ClSymbolImpl.java:130)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:123)
	at cursive.psi.impl.symbols.ClSymbolImpl.resolve(ClSymbolImpl.java:193)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:315)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:95)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:200)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:60)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:87)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:380)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1154)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:371)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:368)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:344)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:193)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by cursiveclojure** [comment]
I just tested this with the latest build, and this seems to have been fixed by the changes I'm making to the form parsing.
