### ISSUE TITLE
Repeatedly throwing exception

### ISSUE THREAD

**Issue by georgewfraser** [cursiveclojure/cursive#443]
```
Element: class com.intellij.sql.psi.impl.SqlFileImpl because: LightVirtualFile: db-console:/4ce5079f/fd610488-be7d-4b00-a51e-cd2fd9742896/ is invalid
invalidated at: no info: Element: class com.intellij.sql.psi.impl.SqlFileImpl because: LightVirtualFile: db-console:/4ce5079f/fd610488-be7d-4b00-a51e-cd2fd9742896/ is invalid
invalidated at: no info
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.sql.psi.impl.SqlFileImpl because: LightVirtualFile: db-console:/4ce5079f/fd610488-be7d-4b00-a51e-cd2fd9742896/ is invalid
invalidated at: no info
	at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:461)
	at com.intellij.psi.util.PsiUtilBase.getPsiFileInEditor(PsiUtilBase.java:121)
	at plugin.actions.paredit$create_widget$update_status__2666.invoke(paredit.clj:576)
	at plugin.actions.paredit$create_widget$fn__2671.invoke(paredit.clj:585)
	at plugin.actions.paredit.proxy$com.intellij.openapi.wm.impl.status.EditorBasedWidget$CustomStatusBarWidget$StatusBarWidget$Multiframe$3bca5c47.fileClosed(Unknown Source)
	at sun.reflect.GeneratedMethodAccessor166.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:228)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:234)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:219)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:216)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:209)
	at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:131)
	at com.sun.proxy.$Proxy79.fileClosed(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.EditorWindow$2$1.run(EditorWindow.java:339)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13$1.run(FileEditorManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:648)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:632)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:602)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$7.run(FocusManagerImpl.java:498)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2053)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:476)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:471)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$13.run(FileEditorManagerImpl.java:955)
	at com.intellij.openapi.util.BusyObject$Impl$Simple.execute(BusyObject.java:123)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.notifyPublisher(FileEditorManagerImpl.java:951)
	at com.intellij.openapi.fileEditor.impl.EditorWindow$2.run(EditorWindow.java:332)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runChange(FileEditorManagerImpl.java:1602)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.java:291)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.closeFile(EditorsSplitters.java:571)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$7.run(FileEditorManagerImpl.java:601)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runChange(FileEditorManagerImpl.java:1602)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:598)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$600(FileEditorManagerImpl.java:100)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$6.run(FileEditorManagerImpl.java:589)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:124)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:99)
	at com.intellij.openapi.command.impl.CommandProcessorImpl.executeCommand(CommandProcessorImpl.java:85)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:586)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:575)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeAllFiles(FileEditorManagerImpl.java:1861)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.projectClosed(FileEditorManagerImpl.java:1421)
	at com.intellij.openapi.project.impl.ProjectImpl.d(ProjectImpl.java:425)
	at com.intellij.openapi.project.impl.ProjectImpl.access$300(ProjectImpl.java:74)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectClosed(ProjectImpl.java:453)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.projectClosed(ProjectManagerImpl.java:164)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.f(ProjectManagerImpl.java:1083)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$1600(ProjectManagerImpl.java:83)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$17.run(ProjectManagerImpl.java:982)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:971)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDispose(ProjectManagerImpl.java:1003)
	at com.intellij.ide.impl.ProjectUtil.closeAndDispose(ProjectUtil.java:85)
	at com.intellij.openapi.wm.impl.IdeFrameImpl$4$1.run(IdeFrameImpl.java:249)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by cursiveclojure** [comment]
I have not been able to reproduce this issue, but I've added some defensive code which will hopefully avoid the problem. If not, please re-open this issue.
