### ISSUE TITLE
Can't create new run configuration on 12.1.6

### ISSUE THREAD

**Issue by cursiveclojure** [cursiveclojure/cursive#509]
Reported via email:

> Edit Configurations->Add New Configuration->Clojure Repl->Local
> Nothing happens when I click. Same thing for Remote.

```
java.lang.NullPointerException
	at plugin.repl.process_runner$create_local_editor$fn__8008.invoke(process_runner.clj:179)
	at plugin.repl.process_runner.proxy$com.intellij.openapi.options.SettingsEditor$0.resetEditorFrom(Unknown Source)
	at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:85)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.resetEditorFrom(ConfigurationSettingsEditor.java:235)
	at com.intellij.execution.impl.ConfigurationSettingsEditor$ConfigToSettingsWrapper.resetEditorFrom(ConfigurationSettingsEditor.java:224)
	at com.intellij.openapi.options.CompositeSettingsEditor.resetEditorFrom(CompositeSettingsEditor.java:47)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.resetEditorFrom(ConfigurationSettingsEditorWrapper.java:101)
	at com.intellij.execution.impl.ConfigurationSettingsEditorWrapper.resetEditorFrom(ConfigurationSettingsEditorWrapper.java:45)
	at com.intellij.openapi.options.SettingsEditor.resetFrom(SettingsEditor.java:85)
	at com.intellij.openapi.options.SettingsEditorConfigurable.reset(SettingsEditorConfigurable.java:50)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.reset(SingleConfigurationConfigurable.java:108)
	at com.intellij.execution.impl.SingleConfigurationConfigurable.editSettings(SingleConfigurationConfigurable.java:89)
	at com.intellij.execution.impl.RunConfigurable.a(RunConfigurable.java:1028)
	at com.intellij.execution.impl.RunConfigurable.b(RunConfigurable.java:1062)
	at com.intellij.execution.impl.RunConfigurable.access$2200(RunConfigurable.java:78)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$2$2.onChosen(RunConfigurable.java:1148)
	at com.intellij.execution.impl.RunConfigurable$MyToolbarAddAction$2$2.onChosen(RunConfigurable.java:1136)
	at com.intellij.ui.popup.list.ListPopupImpl.a(ListPopupImpl.java:359)
	at com.intellij.ui.popup.list.ListPopupImpl.handleSelect(ListPopupImpl.java:327)
	at com.intellij.ui.popup.list.ListPopupImpl$MyMouseListener.mouseReleased(ListPopupImpl.java:449)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:273)
	at java.awt.Component.processMouseEvent(Component.java:6414)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3275)
	at com.intellij.ui.popup.list.ListPopupImpl$MyList.processMouseEvent(ListPopupImpl.java:504)
	at java.awt.Component.processEvent(Component.java:6179)
	at java.awt.Container.processEvent(Container.java:2084)
	at java.awt.Component.dispatchEventImpl(Component.java:4776)
	at java.awt.Container.dispatchEventImpl(Container.java:2142)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4618)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4279)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4209)
	at java.awt.Container.dispatchEventImpl(Container.java:2128)
	at java.awt.Window.dispatchEventImpl(Window.java:2492)
	at java.awt.Component.dispatchEvent(Component.java:4604)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:717)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:690)
	at java.awt.EventQueue$3.run(EventQueue.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:687)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:700)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:521)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1049)
	at java.awt.Dialog$3.run(Dialog.java:1101)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1099)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:706)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:399)
	at com.intellij.openapi.ui.DialogWrapper.showAndGetOk(DialogWrapper.java:1460)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1435)
	at com.intellij.execution.actions.EditRunConfigurationsAction.actionPerformed(EditRunConfigurationsAction.java:46)
	at com.intellij.ui.popup.PopupFactoryImpl$ActionPopupStep$1.run(PopupFactoryImpl.java:726)
	at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1253)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:616)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:597)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:567)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:55)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:102)
	at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:700)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:525)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by cursiveclojure** [comment]
I believe this is now fixed.
