### ISSUE TITLE
error when getting deps

### ISSUE THREAD

**Issue by ashyoff** [cursiveclojure/cursive#560]
Hello, I got errors when I get my project loaded in Idea, below is the stack trace:
```
java.lang.Double cannot be cast to java.lang.String: java.lang.Double cannot be cast to java.lang.String
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.String
	at cursive.leiningen.project.LeiningenProjectsManager.getInterProjectDependencies(LeiningenProjectsManager.java:449)
	at cursive.leiningen.project.LeiningenProjectsManager.access$700(LeiningenProjectsManager.java:32)
	at cursive.leiningen.project.LeiningenProjectsManager$3.run(LeiningenProjectsManager.java:266)
	at cursive.leiningen.LeiningenUtil$4$1.run(LeiningenUtil.java:101)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:471)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$2.run(ProgressManagerImpl.java:178)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:171)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$8.run(ProgressManagerImpl.java:380)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:419)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:662)
	at com.intellij.openapi.application.impl.ApplicationImpl$1$1.run(ApplicationImpl.java:149)
```

Here's my project.clj file
```clojure
(defproject mytest "x.y.z-not_used"
  :description "A test project"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :main my.testproject..core
  :aot [my.testproject.core]
  :dependencies [[org.clojure/clojure "1.5.1"]
                 [org.clojure/core.async "0.1.267.0-0d7780-alpha"]
                 [org.clojure/core.incubator "0.1.3"]
                 [org.clojure/data.json "0.2.2"]
                 [org.clojure/tools.logging "0.2.6"]
                 [org.clojure/tools.cli "0.2.4"]
                 [org.slf4j/slf4j-api "1.7.2"]
                 [org.slf4j/log4j-over-slf4j "1.7.2"]
                 ;[org.slf4j/jcl-over-slf4j "1.7.2"]
                 [ch.qos.logback/logback-classic "1.0.9"]
                 [prismatic/plumbing "0.1.0"]
                 ;[de.kotka/lazymap "3.1.1"]
                 [korma "0.3.0-beta15"]
                 [org.clojure/java.jdbc "0.2.3"]
                 [org.clojure/data.csv "0.1.2"]
                 [mysql/mysql-connector-java "5.1.24"]
                 [compojure "1.1.5"]
                 [ring/ring-core "1.1.8"]
                 [ring/ring-jetty-adapter "1.1.8"]
                 [clj-time "0.5.0"]
                 [clamq/clamq-jms "0.4"]
                 [jdom/jdom 1.0]
                 [javax.jms/jms "1.1"]
                 [org.apache.activemq/activemq-client "5.9.1"]
                 [clj-http "0.7.8"]
                 [com.github.kyleburton/clj-xpath "1.4.1"]
                 [instaparse "1.1.0"]
                 [my.company.jpegtools/iptc-metadata-processor "1.55.1"]
                 [my.company.tools/feed-lib "1.54.1" :exclusions [log4j my.company.prod/go-live]]
                 [my.company.common/common-lib "1.42.1" :exclusions [[log4j]]]
                 [my-search/commons "1.3.0"]
                 [commons-lang "2.6"]
                 [org.jasypt/jasypt "1.9.0"]
                 [ring.velocity "0.1.2"]
                 [com.my.company/logic-conversion "1.54.1" :exclusions [[log4j]]]]
  :profiles {:dev {:dependencies [[ring-mock "0.1.3"]]}}
  :plugins [[lein-ring "0.8.3"]
            [lein-libdir "0.1.1"]
            [lein-cloverage "1.0.2"]
	    [no-man-is-an-island/lein-eclipse "2.0.0"]]
  ;:ring {:handler my.testproject.control/controller}
  :repositories {"blahblahblah" "http://10.90.0.160:9999/repository/"
                 "atestrepo" "http://a.test.repo:10000/repository/"})
```

**Comment by cursiveclojure** [comment]
The problem is here: `[jdom/jdom 1.0]` - `1.0` should be `"1.0"`.

**Comment by ashyoff** [comment]
Many thanks. That's the problem.
