### ISSUE TITLE
Running REPL / Runner Run is not registered

### ISSUE THREAD

**Issue by kernelp4nic** [cursiveclojure/cursive#599]
Hello,

I just upgraded intellij to 14 version (also cursive repo to 14) and I'm seein an error when I try to run the REPL, this is the stack:

```
2014-11-05 23:37:44,317 [ 178242]  ERROR - ution.ui.RunContentManagerImpl - Runner Run is not registered 
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.execution.ui.RunContentManagerImpl.getContentManagerForRunner(RunContentManagerImpl.java:474)
	at com.intellij.execution.ui.RunContentManagerImpl.getReuseContent(RunContentManagerImpl.java:383)
	at cursive.repl.runner.LocalProgramRunner$1.run(LocalProgramRunner.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
```

**Comment by kliniki-online** [comment]
+1
windows 8.1
intellij idea 14.0.2

```
Runner Run is not registered
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.execution.ui.RunContentManagerImpl.a(RunContentManagerImpl.java:479)
	at com.intellij.execution.ui.RunContentManagerImpl.getReuseContent(RunContentManagerImpl.java:384)
	at cursive.repl.runner.LocalProgramRunner$1.run(LocalProgramRunner.java:73)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```
