### ISSUE TITLE
Can't open root project.clj for nathanmarz/cascalog

### ISSUE THREAD

**Issue by danielcompton** [cursiveclojure/cursive#612]
On a clean checkout of https://github.com/nathanmarz/cascalog, trying to open project.clj gets an error and prevents opening. Even if there is an error loading the project, stopping IntelliJ from opening the project means I need to open another editor to fix the project.clj file before opening IntelliJ again.

```
Error loading /Users/Daniel/Developer/clojure/cascalog/project.clj: Error loading /Users/Daniel/Developer/clojure/cascalog/project.clj
java.lang.Exception: Error loading /Users/Daniel/Developer/clojure/cascalog/project.clj
	at leiningen.core.project$read$fn__3326.invoke(project.clj:696)
	at leiningen.core.project$read.invoke(project.clj:693)
	at leiningen.core.project$read.invoke(project.clj:703)
	at plugin.leiningen$load_project.invoke(leiningen.clj:65)
	at clojure.lang.Var.invoke(Var.java:415)
	at cursive.leiningen.utils.Interop.loadProject(Interop.java:20)
	at cursive.leiningen.project.LeiningenProject.reload(LeiningenProject.java:38)
	at cursive.leiningen.project.LeiningenProject.<init>(LeiningenProject.java:34)
	at cursive.leiningen.project.LeiningenProject.create(LeiningenProject.java:29)
	at cursive.leiningen.project.LeiningenProjectOpenProcessor.doQuickImport(LeiningenProjectOpenProcessor.java:36)
	at com.intellij.projectImport.ProjectOpenProcessorBase.doOpenProject(ProjectOpenProcessorBase.java:132)
	at com.intellij.ide.impl.ProjectUtil.openOrImport(ProjectUtil.java:123)
	at com.intellij.ide.CommandLineProcessor.doOpenFileOrProject(CommandLineProcessor.java:80)
	at com.intellij.ide.CommandLineProcessor.processExternalCommandLine(CommandLineProcessor.java:185)
	at com.intellij.openapi.application.impl.ApplicationImpl$3$1.run(ApplicationImpl.java:256)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.io.FileNotFoundException: VERSION (No such file or directory), compiling:(project.clj:1:14)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3463)
	at clojure.lang.Compiler$DefExpr.eval(Compiler.java:408)
	at clojure.lang.Compiler.eval(Compiler.java:6624)
	at clojure.lang.Compiler.load(Compiler.java:7064)
	at clojure.lang.Compiler.loadFile(Compiler.java:7020)
	at clojure.lang.RT$3.invoke(RT.java:318)
	at leiningen.core.project$read$fn__3326.invoke(project.clj:694)
	... 32 more
Caused by: java.io.FileNotFoundException: VERSION (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:120)
	at clojure.java.io$fn__8638.invoke(io.clj:233)
	at clojure.java.io$fn__8577$G__8542__8584.invoke(io.clj:73)
	at clojure.java.io$fn__8650.invoke(io.clj:262)
	at clojure.java.io$fn__8577$G__8542__8584.invoke(io.clj:73)
	at clojure.java.io$fn__8612.invoke(io.clj:169)
	at clojure.java.io$fn__8551$G__8546__8558.invoke(io.clj:73)
	at clojure.java.io$reader.doInvoke(io.clj:106)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:161)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:619)
	at clojure.core$slurp.doInvoke(core.clj:6278)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at clojure.lang.AFn.applyToHelper(AFn.java:161)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.Compiler$InvokeExpr.eval(Compiler.java:3458)
	... 38 more

```

**Comment by danielcompton** [comment]
Dupe of #333.
