### ISSUE TITLE
[0.1.42] Cannot run REPL when more then one Leiningen project is added

### ISSUE THREAD

**Issue by kassapo** [cursiveclojure/cursive#644]
Hi

I am using #IU-138.225 on the Mac. When running a repl in any configuration this is what happens:

java.lang.NullPointerException
	at clojure.lang.Reflector.invokeNoArgInstanceMember(Reflector.java:296)
	at leiningen.core.classpath$exclusion_for_range.invoke(classpath.clj:228)
	at leiningen.core.classpath$exclusion_for_override.invoke(classpath.clj:238)
	at clojure.core$map$fn__4207.invoke(core.clj:2485)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at leiningen.core.classpath$pedantic_print_overrides.invoke(classpath.clj:266)
	at clojure.lang.AFn.applyToHelper(AFn.java:161)
	at clojure.lang.AFn.applyTo(AFn.java:151)
	at clojure.core$apply.invoke(core.clj:617)
	at clojure.core$memoize$fn__5049.doInvoke(core.clj:5735)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at leiningen.core.classpath$pedantic_do.invoke(classpath.clj:279)
	at leiningen.core.classpath$get_dependencies.doInvoke(classpath.clj:300)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.lang.AFn.applyToHelper(AFn.java:163)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:621)
	at leiningen.core.classpath$dependency_hierarchy.doInvoke(classpath.clj:363)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at plugin.leiningen$load_dependencies$fn__7096.invoke(leiningen.clj:158)
	at plugin.leiningen$load_dependencies_STAR_.invoke(leiningen.clj:86)
	at plugin.leiningen$load_dependencies.invoke(leiningen.clj:154)
	at clojure.lang.Var.invoke(Var.java:431)
	at cursive.leiningen.utils.Interop.loadDependencies(Interop.java:29)
	at cursive.leiningen.module.ModuleCreationUtils.importModule(ModuleCreationUtils.java:677)
	at cursive.leiningen.project.LeiningenProjectsManager$3.run(LeiningenProjectsManager.java:293)
	at cursive.leiningen.LeiningenUtil$4$1.run(LeiningenUtil.java:101)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$TaskRunnable.run(ProgressManagerImpl.java:609)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$3.run(ProgressManagerImpl.java:194)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcess(ProgressManagerImpl.java:181)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$9.run(ProgressManagerImpl.java:518)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)

**Comment by cursiveclojure** [comment]
I believe this should be fixed in 0.1.64. If that's not the case, feel free to re-open.
