### ISSUE TITLE
structural editing breaks

### ISSUE THREAD

**Issue by kovasb** [cursiveclojure/cursive#658]
Sometimes structural editing stops working. Closing and reopening file fixes it. 

Heres the info from "IDE fatal errors"

Invalid stub element type in index: file:///Users/kovasb/repo/gamma/src/gamma/compiler.clj; found: ClKeyword
file stamp: 371028; file size: 4319; file modCount: 1417035470000
saved: true; doc stamp: 371028; doc size: 4319; committed: true
psiFile size: 4319; viewProvider stamp: 371028; ast loaded: true; ast parsed: true; ast size: 4319
indexing info: indexed at 1417035470000 with size 4319
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:113)
	at com.intellij.psi.stubs.StubIndexImpl.reportStubPsiMismatch(StubIndexImpl.java:492)
	at com.intellij.psi.stubs.StubIndex.safeGet(StubIndex.java:101)
	at plugin.indexes.namespaces$namespaces_by_name.invoke(namespaces.clj:24)
	at plugin.indexes.namespaces$ns_by_name.invoke(namespaces.clj:30)
	at plugin.extensions.clojure.core.resolve$require_symbols$aliases__4762$fn__4763.invoke(resolve.clj:409)
	at plugin.extensions.clojure.core.resolve$prefix_symbols.invoke(resolve.clj:375)
	at plugin.extensions.clojure.core.resolve$require_symbols$aliases__4762.invoke(resolve.clj:409)
	at plugin.dependencies$parse_libspec.invoke(dependencies.clj:84)
	at plugin.extensions.clojure.core.resolve$require_symbols$fn__4769.invoke(resolve.clj:420)
	at clojure.core$map$fn__4207.invoke(core.clj:2487)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$apply.invoke(core.clj:617)
	at plugin.extensions.clojure.core.resolve$require_symbols.invoke(resolve.clj:421)
	at plugin.extensions.clojure.core.resolve$use_symbols.invoke(resolve.clj:455)
	at plugin.extensions.clojure.core.resolve$fn__4825.invoke(resolve.clj:548)
	at plugin.resolve$list_resolve_symbols$fn__8703$fn__8706.invoke(resolve.clj:218)
	at clojure.core$map$fn__4207.invoke(core.clj:2487)
	at clojure.lang.LazySeq.sval(LazySeq.java:42)
	at clojure.lang.LazySeq.seq(LazySeq.java:60)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1654)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invoke(core.clj:619)
	at plugin.resolve$list_resolve_symbols$fn__8703.invoke(resolve.clj:216)
	at plugin.psi$cached_value$reify__8007.compute(psi.clj:412)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:81)
	at plugin.psi$cached_value.doInvoke(psi.clj:415)
	at clojure.lang.RestFn.invoke(RestFn.java:494)
	at plugin.resolve$list_resolve_symbols.invoke(resolve.clj:211)
	at plugin.resolve$resolve_from_symbols.invoke(resolve.clj:238)
	at plugin.resolve.lists$process_list_declarations.invoke(lists.clj:40)
	at clojure.lang.Var.invoke(Var.java:431)
	at cursive.psi.impl.list.ClListBaseImpl.processDeclarations(ClListBaseImpl.java:107)
	at plugin.resolve$process_declarations.invoke(resolve.clj:62)
	at plugin.resolve.symbol.editor.clj$editor_resolver$reify__3756$fn__3775.invoke(clj.clj:266)
	at plugin.resolve.symbol.common$tree_walk.invoke(common.clj:41)
	at plugin.resolve.symbol.editor.clj$editor_resolver$reify__3756.resolve_unqualified(clj.clj:265)
	at plugin.resolve.symbol$resolve_normal_symbol.invoke(symbol.clj:96)
	at plugin.resolve.symbol$resolve_symbol.invoke(symbol.clj:120)
	at clojure.lang.Var.invoke(Var.java:419)
	at cursive.psi.impl.symbols.SymbolReference$MyResolver.resolve(SymbolReference.java:67)
	at cursive.psi.impl.symbols.SymbolReference$MyResolver.resolve(SymbolReference.java:64)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:103)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:131)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:123)
	at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
	at plugin.annotator$annotate_symbol.invoke(annotator.clj:286)
	at plugin.annotator$fn__4267.invoke(annotator.clj:322)
	at plugin.annotator$fn__4248$G__4243__4255.invoke(annotator.clj:313)
	at plugin.annotator$initialise$reify__4271.annotate(annotator.clj:337)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.runAnnotators(DefaultHighlightVisitor.java:160)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.visit(DefaultHighlightVisitor.java:103)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$5.run(GeneralHighlightingPass.java:296)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:383)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:61)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:389)
	at com.intellij.codeInsight.daemon.impl.DefaultHighlightVisitor.analyze(DefaultHighlightVisitor.java:87)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:386)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.access$300(GeneralHighlightingPass.java:61)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass$6.run(GeneralHighlightingPass.java:389)
	at com.intellij.codeInsight.daemon.impl.RefCountHolder.analyze(RefCountHolder.java:298)
	at com.intellij.codeInsight.daemon.impl.analysis.HighlightVisitorImpl.analyze(HighlightVisitorImpl.java:161)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.analyzeByVisitors(GeneralHighlightingPass.java:386)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectHighlights(GeneralHighlightingPass.java:374)
	at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:214)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:86)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:61)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:355)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1166)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:346)
	at com.intellij.openapi.progress.ProgressManager.executeProcessUnderProgress(ProgressManager.java:209)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:212)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:343)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:319)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:194)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

**Comment by cursiveclojure** [comment]
I'm assuming this was fixed by invalidating the caches - if not, please re-open.
