### ISSUE TITLE
Cursive cannot find lein project, given proper project.clj

### ISSUE THREAD

**Issue by jcswart** [cursiveclojure/cursive#679]
I am trying to import a project, started by someone else.  

Cursive, though pointed to the path of the project.clj file cannot find anything to import.
![screen shot 2014-12-15 at 18 04 51](https://cloud.githubusercontent.com/assets/1610469/5445782/e7ff01b4-8484-11e4-9f08-1bb30ffe3160.png)

What could cause this issue?

Other projects work fine.

**Comment by cursiveclojure** [comment]
Did you ever get this resolved? If not, could you reproduce it and check your log for exceptions? Help->Show log in Finder/Explorer.

**Comment by cursiveclojure** [comment]
Assuming this is resolved, please re-open if not.

**Comment by bfabry** [comment]
Hi, getting the same error, this stack trace in the logs.

```
2015-04-29 23:35:19,848 [ 523496]  ERROR - ursive.leiningen.LeiningenUtil - No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil 
java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:567)
	at clojure.java.io$fn__9072$G__9054__9079.invoke(io.clj:69)
	at clojure.java.io$reader.doInvoke(io.clj:102)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at leiningen.core.main$leiningen_version.invoke(main.clj:313)
	at clojure.lang.Var.invoke(Var.java:375)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1053)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:616)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1073)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1073)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1081)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1081)
	at clojure.lang.LispReader.read(LispReader.java:183)
	at clojure.lang.RT.readString(RT.java:1785)
	at clojure.core$read_string.invoke(core.clj:3648)
	at leiningen.core.utils$read_file.invoke(utils.clj:30)
	at leiningen.core.user$fn__10368.invoke(user.clj:67)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$memoize$fn__5467.doInvoke(core.clj:6079)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at leiningen.core.user$fn__10371.invoke(user.clj:85)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$memoize$fn__5467.doInvoke(core.clj:6079)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at leiningen.core.project$read_profiles.invoke(project.clj:654)
	at leiningen.core.project$project_with_profiles.invoke(project.clj:798)
	at cursive.leiningen$read_project.invoke(leiningen.clj:78)
	at cursive.leiningen$load_project.invoke(leiningen.clj:86)
	at clojure.lang.Var.invoke(Var.java:379)
	at cursive.leiningen.utils.Interop.loadProject(Interop.java:22)
	at cursive.leiningen.project.LeiningenProject.reload(LeiningenProject.java:38)
	at cursive.leiningen.project.LeiningenProject.<init>(LeiningenProject.java:34)
	at cursive.leiningen.project.LeiningenProject.create(LeiningenProject.java:29)
	at cursive.leiningen.project.LeiningenProjectsManager.importLeiningenProjects(LeiningenProjectsManager.java:112)
	at cursive.leiningen.project.LeiningenModuleBuilder$1.run(LeiningenModuleBuilder.java:66)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivity(StartupManagerImpl.java:339)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$700(StartupManagerImpl.java:59)
	at com.intellij.ide.startup.impl.StartupManagerImpl$3.run(StartupManagerImpl.java:174)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:146)
	at com.intellij.ide.startup.impl.StartupManagerImpl.queueSmartModeActivity(StartupManagerImpl.java:171)
	at com.intellij.ide.startup.impl.StartupManagerImpl.access$1000(StartupManagerImpl.java:59)
	at com.intellij.ide.startup.impl.StartupManagerImpl$4.run(StartupManagerImpl.java:205)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:269)
	at com.intellij.openapi.project.DumbServiceImpl.access$800(DumbServiceImpl.java:52)
	at com.intellij.openapi.project.DumbServiceImpl$9.run(DumbServiceImpl.java:439)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:199)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
2015-04-29 23:35:19,849 [ 523497]  ERROR - ursive.leiningen.LeiningenUtil - IntelliJ IDEA 14.1.2  Build #IC-141.713.2 
2015-04-29 23:35:19,849 [ 523497]  ERROR - ursive.leiningen.LeiningenUtil - JDK: 1.6.0_65 
2015-04-29 23:35:19,849 [ 523497]  ERROR - ursive.leiningen.LeiningenUtil - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-04-29 23:35:19,849 [ 523497]  ERROR - ursive.leiningen.LeiningenUtil - Vendor: Apple Inc. 
2015-04-29 23:35:19,849 [ 523497]  ERROR - ursive.leiningen.LeiningenUtil - OS: Mac OS X 
2015-04-29 23:35:19,849 [ 523497]  ERROR - ursive.leiningen.LeiningenUtil - Last Action: ShowLog 
2015-04-29 23:35:20,154 [ 523802]   INFO - CompilerWorkspaceConfiguration - Available processors: 4 
 ```

Hope this is useful!
