### ISSUE TITLE
File is permantly reindexed

### ISSUE THREAD

**Issue by rogergl** [cursiveclojure/cursive#689]
```
(ns project.test-helper.datomic-helper

(use '[datomic.api :only [q db] :as d])
(def schema-tx[

               {:db/id #db/id[:db.part/db]
                :db/ident :area/connected
                :db/valueType :db.type/ref
                :db/cardinality :db.cardinality/one
                :db/doc "An area.connection-state value"
                :db.install/_attribute :db.part/db}
               ])
```
I think the problem is the reader macro. Removing it stops the reindexing

**Comment by rogergl** [comment]
Now I get this stack trace with the latest cursive release

please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:848)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:797)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:922)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:999)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:907)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:897)
	at plugin.index$class_by_text_range.invoke(index.clj:393)
	at plugin.intellij.class$class_by_text_range.invoke(class.clj:272)
	at plugin.intellij.class$find_class$fn__4927.invoke(class.clj:284)
	at clojure.core$some.invoke(core.clj:2443)
	at plugin.intellij.class$find_class.invoke(class.clj:282)
	at clojure.lang.Var.invoke(Var.java:415)
	at cursive.psi.changes.ClojureModificationListener.processChange(ClojureModificationListener.java:60)
	at cursive.psi.changes.ClojureModificationListener.treeChanged(ClojureModificationListener.java:37)
	at com.intellij.psi.impl.PsiManagerImpl.a(PsiManagerImpl.java:397)
	at com.intellij.psi.impl.PsiManagerImpl.childReplaced(PsiManagerImpl.java:337)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.a(PsiEventWrapperAspect.java:103)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.update(PsiEventWrapperAspect.java:50)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:175)
	at com.intellij.psi.impl.DocumentCommitProcessor$2.run(DocumentCommitProcessor.java:214)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$8.compute(CodeStyleManagerImpl.java:671)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:119)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$10.compute(CodeStyleManagerImpl.java:706)
	at com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:894)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:702)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:668)
	at com.intellij.psi.impl.DocumentCommitProcessor.doActualPsiChange(DocumentCommitProcessor.java:199)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:135)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:125)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:325)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:132)
	at com.intellij.psi.impl.PsiDocumentManagerBase$3.run(PsiDocumentManagerBase.java:295)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:292)
	at com.intellij.psi.impl.DocumentCommitThread$5.run(DocumentCommitThread.java:531)
	at com.intellij.psi.impl.DocumentCommitThread.commitSynchronously(DocumentCommitThread.java:427)
	at com.intellij.psi.impl.PsiDocumentManagerBase$5.run(PsiDocumentManagerBase.java:377)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
	at com.intellij.psi.impl.PsiDocumentManagerBase.b(PsiDocumentManagerBase.java:369)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitDocument(PsiDocumentManagerBase.java:282)
	at com.intellij.psi.impl.PsiDocumentManagerBase.commitAllDocuments(PsiDocumentManagerBase.java:216)
	at com.intellij.codeInsight.editorActions.EnterHandler.a(EnterHandler.java:165)
	at com.intellij.codeInsight.editorActions.EnterHandler.access$000(EnterHandler.java:53)
	at com.intellij.codeInsight.editorActions.EnterHandler$1.run(EnterHandler.java:75)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect$3.compute(PostprocessReformattingAspect.java:110)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:119)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:107)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:72)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:220)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:220)
	at cursive.repl.toolwindow.actions.REPLEnterAction.doExecute(REPLEnterAction.java:32)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:204)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:36)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:201)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:355)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:435)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:346)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:97)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:108)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:82)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:614)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:663)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:513)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:546)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

**Comment by cursiveclojure** [comment]
Yes, this is a different problem that was introduced in the latest release. I'll fix that for the next drop too.

**Comment by cursiveclojure** [comment]
Is the endless reindexing still a problem for you? I just tried but I can't reproduce it.

**Comment by rogergl** [comment]
Yes it is still a problem andere the cause is still the #db/id reader macro.

**Comment by cursiveclojure** [comment]
Is that the whole problematic file you've pasted above?

**Comment by rogergl** [comment]
No it is just a part of a larger file but still this small part triggers the reindexing.

Von meinem iPhone gesendet

**Comment by cursiveclojure** [comment]
Can you open this project, and see if it reproduces the issue for you? 
http://colinfleming.net/roger/cursive-689.zip

**Comment by rogergl** [comment]
Yes it does, but it behaves differently. Reindex appears permanently. Im my project it stops if i navigate from the source file containing the reader macro to another file and it stops if I delete the reader macro.

BTW: I had to change the project.clj to use username, password instead of gpg.

**Comment by cursiveclojure** [comment]
Hmm, that project doesn't reproduce the issue for me. Can you try File->Invalidate Caches and Restart? If that doesn't fix it, which IntelliJ and Cursive versions are you running?

The project.clj change is unrelated, that's just how you connect to `my.datomic.com`.

**Comment by rogergl** [comment]
Invalidating did not help. I’m using Intellij 14.0.3 and the latest cursive release.

**Comment by cursiveclojure** [comment]
Could you reproduce this issue and send me your log file, please? You can mail it to cursive@cursiveclojure.com.

**Comment by cursiveclojure** [comment]
Actually, if you could reproduce this and take a thread dump too, that would be helpful. Instructions here: https://intellij-support.jetbrains.com/entries/23348667

**Comment by cursiveclojure** [comment]
Could you try this? Help->Configure Debug Log Settings… and add `#com.intellij.openapi.project.DumbServiceImpl` there? Then once you’ve reproduced the problem for a while, could you send me your log file?

**Comment by cursiveclojure** [comment]
This was caused by a strange bug parsing the `data_readers.clj` file from core.contracts 0.0.4, which has all its element commented out. This is fixed for the next build.
