### ISSUE TITLE
IntelliJ IDEA 14.0.2 + Cursive 0.1.43: Sometimes throw IndexNotReadyException during opening leiningen project.

### ISSUE THREAD

**Issue by zhanghuabin** [cursiveclojure/cursive#705]
This is stack as below:

    Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
    com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:848)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:797)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:922)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:999)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:907)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:897)
	at plugin.index$class_by_text_range.invoke(index.clj:393)
	at plugin.intellij.class$class_by_text_range.invoke(class.clj:272)
	at plugin.intellij.class$find_class$fn__4927.invoke(class.clj:284)
	at clojure.core$some.invoke(core.clj:2443)
	at plugin.intellij.class$find_class.invoke(class.clj:282)
	at clojure.lang.Var.invoke(Var.java:415)
	at cursive.psi.changes.ClojureModificationListener.processChange(ClojureModificationListener.java:60)
	at cursive.psi.changes.ClojureModificationListener.treeChanged(ClojureModificationListener.java:37)
	at com.intellij.psi.impl.PsiManagerImpl.a(PsiManagerImpl.java:397)
	at com.intellij.psi.impl.PsiManagerImpl.childReplaced(PsiManagerImpl.java:337)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.a(PsiEventWrapperAspect.java:103)
	at com.intellij.pom.wrappers.PsiEventWrapperAspect.update(PsiEventWrapperAspect.java:50)
	at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:175)
	at com.intellij.psi.impl.DocumentCommitProcessor$2.run(DocumentCommitProcessor.java:214)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$8.compute(CodeStyleManagerImpl.java:671)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:119)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$10.compute(CodeStyleManagerImpl.java:706)
	at com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:894)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:702)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:668)
	at com.intellij.psi.impl.DocumentCommitProcessor.doActualPsiChange(DocumentCommitProcessor.java:199)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:135)
	at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:125)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:325)
	at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:132)
	at com.intellij.psi.impl.PsiDocumentManagerBase$3.run(PsiDocumentManagerBase.java:295)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:974)
	at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:292)
	at com.intellij.psi.impl.DocumentCommitThread$5.run(DocumentCommitThread.java:531)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by cursiveclojure** [comment]
Yes, this was mentioned in #689 - I'll fix this for the next release.

**Comment by zhanghuabin** [comment]
Thank you!
