### ISSUE TITLE
Java Unit Tests with code coverage run very slow with Cursive enabled.

### ISSUE THREAD

**Issue by cursiveclojure** [cursiveclojure/cursive#706]
Reported via email: 

> Today I noticed that execution of even just one unit test class with code coverage is extremely slow in Intellij 14. The unit tests are in a pure-java module with a quite large codebase and no Clojure facet attached, Clojure/Cursive is used in another module of the same (maven based) project with much smaller codebase.
>
> It seems that the tests are running reasonably fast, but at the end the IDE freezes for a few (2-3) minutes.
Disabling the Cursive plugin fixes this and the execution is very fast. There are no other non-stock plugins installed.

Some investigation revealed that IntelliJ had created thread dump logs as described [here](https://intellij-support.jetbrains.com/entries/23348667), the relevant snippet is:

```
        at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.getChildren(VirtualDirectoryImpl.java:283)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:275)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
        at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:296)
        at com.intellij.openapi.vfs.VfsUtilCore.iterateChildrenRecursively(VfsUtilCore.java:244)
        at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:69)
        at com.intellij.util.indexing.FileBasedIndexImpl.iterateIndexableFiles(FileBasedIndexImpl.java:2527)
        at com.intellij.util.indexing.IdFilter.getProjectIdFilter(IdFilter.java:52)
        at plugin.scope$id_filter.invoke(scope.clj:31)
        at plugin.index$all_class_fqns.invoke(index.clj:407)
        at clojure.lang.Var.invoke(Var.java:415)
        at cursive.psi.impl.javaView.ClojureClassFinder.getSubPackages(ClojureClassFinder.java:133)
```

**Comment by cursiveclojure** [comment]
So I couldn't reproduce your problem, but I've made a change in the next build that I think should solve it. I'll optimistically close this, please re-open if you're still seeing the problem.
