### ISSUE TITLE
Can't open Clojure Compiler Preferences pane

### ISSUE THREAD

**Issue by jstaffans** [cursiveclojure/cursive#718]
After a fresh Cursive install, opening the Build / Compiler / Clojure Compiler pane in Preferences only the spinner icon is shown. The IDEA log has this:

```
com.intellij.openapi.project.IndexNotReadyException documentation 
com.intellij.openapi.project.IndexNotReadyException: Please change caller according to com.intellij.openapi.project.IndexNotReadyException documentation
at com.intellij.util.indexing.FileBasedIndexImpl.handleDumbMode(FileBasedIndexImpl.java:842)
at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:791)
at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:916)
at com.intellij.util.indexing.FileBasedIndexImpl.processValuesImpl(FileBasedIndexImpl.java:993)
at com.intellij.util.indexing.FileBasedIndexImpl.getValues(FileBasedIndexImpl.java:861)
at plugin.index$namespace_names.invoke(index.clj:304)
at plugin.index$namespace_names.invoke(index.clj:306)
at clojure.lang.Var.invoke(Var.java:419)
at cursive.compiler.ClojureCompilerConfigurable.reset(ClojureCompilerConfigurable.java:277)
at com.intellij.openapi.options.ex.ConfigurableWrapper.reset(ConfigurableWrapper.java:177)
at com.intellij.openapi.options.newEditor.OptionsEditor.initConfigurable(OptionsEditor.java:514)
at com.intellij.openapi.options.newEditor.OptionsEditor.access$1900(OptionsEditor.java:67)
at com.intellij.openapi.options.newEditor.OptionsEditor$9$1$1.run(OptionsEditor.java:476)
at com.intellij.openapi.application.impl.ApplicationImpl.runEdtSafeAction(ApplicationImpl.java:1093)
at com.intellij.openapi.options.newEditor.OptionsEditor$9$1.run(OptionsEditor.java:469)
at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:908)
at com.intellij.openapi.options.newEditor.OptionsEditor$9.run(OptionsEditor.java:466)
at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:406)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
at java.util.concurrent.FutureTask.run(FutureTask.java:138)
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
at java.lang.Thread.run(Thread.java:695)
at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
2015-01-29 12:24:48,398 [  32988]  ERROR - plication.impl.ApplicationImpl - IntelliJ IDEA 14.0.3  Build #IC-139.1117.1 
2015-01-29 12:24:48,398 [  32988]  ERROR - plication.impl.ApplicationImpl - JDK: 1.6.0_65 
2015-01-29 12:24:48,398 [  32988]  ERROR - plication.impl.ApplicationImpl - VM: Java HotSpot(TM) 64-Bit Server VM 
2015-01-29 12:24:48,398 [  32988]  ERROR - plication.impl.ApplicationImpl - Vendor: Apple Inc. 
2015-01-29 12:24:48,398 [  32988]  ERROR - plication.impl.ApplicationImpl - OS: Mac OS X 
```

**Comment by cursiveclojure** [comment]
Hmm - ok, I'll fix this. In the meantime, you'll be able to open this pane once IntelliJ has finished indexing.

**Comment by jstaffans** [comment]
Yeah, it started working after a while. Just a bit discouraging for first-time users.

Thanks!

**Comment by cursiveclojure** [comment]
Sure, it's not ideal - I'll see if I can work around it.
