### ISSUE TITLE
Clojure/Lein Project Type

### ISSUE THREAD

**Issue by hansgru** [cursiveclojure/cursive#758]
Please add support for a "Clojure/Lein" project type.

This will raise the visibility of the plug-in and make it easier to get started.

**Comment by hansgru** [comment]
Please prioritize this feature in order for Cursive to know that it doesn't need to be started at all if the project is not Clojure specific.

Right now I'm getting so many exceptions: "AssertionError: Already disposed: Project (Disposed)" that I have to deactivate Cursive when using other project types that don't have to do with Clojure.

A few days ago were other exceptions, around the same problem: Cursive interfering when it should not even be started #753

**Comment by cursiveclojure** [comment]
Can you send a stack trace of the AssertionError so I can fix it?

IntelliJ doesn't work like this, unfortunately. Anyone who has used the Kotlin or Scala plugins will be familiar with exceptions from those plugins even in projects containing no Kotlin or Scala source code. This is because the plugin mechanism works on a contributor model, so for example to find a class named "some.package.MyClass" IntelliJ will ask all active plugins if they define that class, i.e. if there is a class by that name defined in Kotlin, Scala, Clojure, or whatever. Some extensions are language specific and are not loaded if not used, but some must be loaded independently of whether source code in the relevant language is ever seen. Cursive eagerly loads more than most plugins because of limitations in Clojure's interop, but even when I fix that some code will always be loaded and run if the plugin is enabled.

**Comment by hansgru** [comment]
> Can you send a stack trace of the AssertionError so I can fix it?

I sent the "automatic" error from IntelliJ directly, but after that IntelliJ seems 
to hide this info, so I paste here from the logs:
```
2015-02-24 14:44:17,351 [21403696]  ERROR - .intellij.util.EventDispatcher - Already disposed: Project (Disposed) xxxxxxx 
java.lang.AssertionError: Already disposed: Project (Disposed) xxxxxxx
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:191)
	at com.intellij.psi.PsiManager.getInstance(PsiManager.java:39)
	at com.intellij.psi.impl.smartPointers.SelfElementInfo$1.compute(SelfElementInfo.java:238)
	at com.intellij.psi.impl.smartPointers.SelfElementInfo$1.compute(SelfElementInfo.java:224)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:920)
	at com.intellij.psi.impl.smartPointers.SelfElementInfo.restoreFileFromVirtual(SelfElementInfo.java:224)
	at com.intellij.psi.impl.smartPointers.SelfElementInfo.restoreFile(SelfElementInfo.java:174)
	at com.intellij.psi.impl.smartPointers.AnchorElementInfo.restoreElement(AnchorElementInfo.java:62)
	at com.intellij.psi.impl.smartPointers.AnchorElementInfo.fastenBelt(AnchorElementInfo.java:105)
	at com.intellij.psi.impl.smartPointers.SmartPsiElementPointerImpl.fastenBelt(SmartPsiElementPointerImpl.java:177)
	at com.intellij.psi.impl.smartPointers.SmartPointerManagerImpl.fastenBelts(SmartPointerManagerImpl.java:67)
	at com.intellij.psi.impl.PsiDocumentManagerBase.beforeDocumentChange(PsiDocumentManagerBase.java:614)
	at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:88)
	at com.intellij.util.EventDispatcher.access$100(EventDispatcher.java:34)
	at com.intellij.util.EventDispatcher$1.invoke(EventDispatcher.java:68)
	at com.sun.proxy.$Proxy19.beforeDocumentChange(Unknown Source)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:746)
	at com.intellij.openapi.editor.impl.DocumentImpl.a(DocumentImpl.java:714)
	at com.intellij.openapi.editor.impl.DocumentImpl.insertString(DocumentImpl.java:498)
	at com.intellij.openapi.editor.actions.EnterAction.insertNewLineAtCaret(EnterAction.java:109)
	at com.intellij.openapi.editor.actions.EnterAction$Handler.executeWriteAction(EnterAction.java:50)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:220)
	at com.intellij.codeInsight.editorActions.EnterHandler.a(EnterHandler.java:152)
	at com.intellij.codeInsight.editorActions.EnterHandler.access$000(EnterHandler.java:53)
	at com.intellij.codeInsight.editorActions.EnterHandler$1.run(EnterHandler.java:75)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect$3.compute(PostprocessReformattingAspect.java:110)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:119)
	at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:107)
	at com.intellij.codeInsight.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:72)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:220)
	at com.intellij.codeInsight.template.impl.editorActions.EnterHandler.executeWriteAction(EnterHandler.java:49)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler$1.run(EditorWriteActionHandler.java:64)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at com.intellij.openapi.editor.actionSystem.EditorWriteActionHandler.doExecute(EditorWriteActionHandler.java:47)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:220)
	at cursive.repl.toolwindow.actions.REPLEnterAction.doExecute(REPLEnterAction.java:32)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3$1.perform(EditorActionHandler.java:204)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.doIfEnabled(EditorActionHandler.java:107)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.access$000(EditorActionHandler.java:36)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler$3.perform(EditorActionHandler.java:201)
	at com.intellij.openapi.editor.impl.CaretModelImpl$3.run(CaretModelImpl.java:355)
	at com.intellij.openapi.editor.impl.CaretModelImpl.doWithCaretMerging(CaretModelImpl.java:435)
	at com.intellij.openapi.editor.impl.CaretModelImpl.runForEachCaret(CaretModelImpl.java:346)
	at com.intellij.openapi.editor.actionSystem.EditorActionHandler.execute(EditorActionHandler.java:198)
	at com.intellij.openapi.editor.actionSystem.EditorAction$1.run(EditorAction.java:97)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:108)
	at com.intellij.openapi.editor.actionSystem.EditorAction.actionPerformed(EditorAction.java:82)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:614)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:663)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.d(IdeKeyEventDispatcher.java:513)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:211)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:546)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
2015-02-24 14:44:17,355 [21403700]  ERROR - .intellij.util.EventDispatcher - IntelliJ IDEA 14.0.3  Build #IU-139.1117.1 
2015-02-24 14:44:17,355 [21403700]  ERROR - .intellij.util.EventDispatcher - JDK: 1.7.0_75 
2015-02-24 14:44:17,356 [21403701]  ERROR - .intellij.util.EventDispatcher - VM: Java HotSpot(TM) Server VM 
2015-02-24 14:44:17,356 [21403701]  ERROR - .intellij.util.EventDispatcher - Vendor: Oracle Corporation 
2015-02-24 14:44:17,357 [21403702]  ERROR - .intellij.util.EventDispatcher - OS: Windows 7 
2015-02-24 14:44:17,357 [21403702]  ERROR - .intellij.util.EventDispatcher - Last Action: EditorEnter 
2015-02-24 14:44:17,357 [21403702]  ERROR - .intellij.util.EventDispatcher - Current Command: Typing 
```
> IntelliJ doesn't work like this, unfortunately. ...

Thank you for the detailed explanation. 

Nevertheless, from the user's perspective, a Clojure/Lein project type still makes very much sense IMO, the same way there's a Groovy/Grails/Gradle one.

**Comment by cursiveclojure** [comment]
Interesting, that exception doesn't actually seem to be a Cursive exception at all. Cursive does appear in the stacktrace (REPLEnterAction) so IDEA may report it as being Cursive specific, but on that line Cursive delegates to the default implementation because it's not in a Clojure context. When do you receive this?

**Comment by hansgru** [comment]
> Interesting, that exception doesn't actually seem to be a Cursive exception at all....so IDEA may report it as being Cursive specific ..

It did, so that's why I commented this.

> When do you receive this?

As you can see from the log timestamps it was on 24 Feb. There were exceptions the entire day - the above one is just one of them.

**Comment by cursiveclojure** [comment]
This is fixed in the next build. Projects can now be created as plain Clojure projects with an attached Clojure library, or can be created with Leiningen either as a plain lein project or using a template.
