### ISSUE TITLE
Exception when running the Luminus guestbook application with 'lein ring server'

### ISSUE THREAD

**Issue by frickm** [cursiveclojure/cursive#761]
added: the same happens for a 'pure' compojure application.

This is the simplest way of reproducing the error. Trying to use Luminus for a simple web-app I created a new application with `lein new luminus guestbook +h2` like in the tutorial. It can be started with `lein ring server` from the command line, but if I try to do this from within cursive I get an exception with the following stacktrace:
```
Exception in thread "main" java.io.FileNotFoundException: ring (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:131)
	at java.io.FileInputStream.<init>(FileInputStream.java:87)
	at clojure.lang.Compiler.loadFile(Compiler.java:7083)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$script_opt.invoke(main.clj:336)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at clojure.lang.Var.invoke(Var.java:394)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)

Process finished with exit code 1
No nREPL ack received
```
I provided the Parameters: 'ring server' in the run-config, which should be right. I can run a 'pure' REPL and then start the server 'by hand' with (start-server).

**Comment by cursiveclojure** [comment]
It looks like you're adding those parameters to a REPL configuration - that won't work. You'll need to run the server using a Leiningen run configuration, and then run a REPL separately. Does `lein ring server` normally start an nREPL server?

**Comment by danielcompton** [comment]
Looks like this might be incorrect usage of REPL configuration. May be able to be closed?

**Comment by cursiveclojure** [comment]
Yeah, please re-open if you think this is incorrect.
