### ISSUE TITLE
cljx compilationbroken in 0.1.49

### ISSUE THREAD

**Issue by sveri** [cursiveclojure/cursive#786]
Hi,

after updating to the latest version of cursive I get this stacktrace when running the REPL of my project.
Running `lein repl` from the project folder command line works as expected. The only change I can see is the updated cursive version.

Exception in thread "main" java.io.FileNotFoundException: Could not locate cljx/core__init.class or cljx/core.clj on classpath: , compiling:(C:\Users\sveri\.IdeaIC14\system\tmp\form-init4361645874106950598.clj:1:109)
	at clojure.lang.Compiler.load(Compiler.java:7142)
	at clojure.lang.Compiler.loadFile(Compiler.java:7086)
	at clojure.main$load_script.invoke(main.clj:274)
	at clojure.main$init_opt.invoke(main.clj:279)
	at clojure.main$initialize.invoke(main.clj:307)
	at clojure.main$null_opt.invoke(main.clj:342)
	at clojure.main$main.doInvoke(main.clj:420)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
Caused by: java.io.FileNotFoundException: Could not locate cljx/core__init.class or cljx/core.clj on classpath: 
	at clojure.lang.RT.load(RT.java:443)
	at clojure.lang.RT.load(RT.java:411)
	at clojure.core$load$fn__5066.invoke(core.clj:5641)
	at clojure.core$load.doInvoke(core.clj:5640)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5446)
	at clojure.core$load_lib$fn__5015.invoke(core.clj:5486)
	at clojure.core$load_lib.doInvoke(core.clj:5485)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$load_libs.doInvoke(core.clj:5524)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$require.doInvoke(core.clj:5607)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval7.invoke(form-init4361645874106950598.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6703)
	at clojure.lang.Compiler.eval(Compiler.java:6692)
	at clojure.lang.Compiler.load(Compiler.java:7130)
	... 16 more

Process finished with exit code 1

**Comment by sveri** [comment]
Changing this line:

    :prep-tasks [["cljx" "once"] "javac" "compile"]
to this line
    :prep-tasks ["javac" "compile"] 

in my project.clj makes it work again.

**Comment by cursiveclojure** [comment]
I don't think that anything has changed that would affect this. Are you able to share your `project.clj`, or at least the cljx-specific parts of it?

**Comment by sveri** [comment]
Hi,

I just retested by generating a new closp project with `lein new closp foobar`.
As you can see: <https://clojars.org/closp/lein-template> this is from the end of february and it was definitly working.

I recognized this error in this project: <https://github.com/sveri/siwf/blob/master/project.clj> and you can see all the cljx config there.
It may be that I configured it wrong, however, I am pretty sure your latest cursive updated triggered this issue.

**Comment by sveri** [comment]
After updating your plugin (downgrading leiningen) cljx compilation works again for me.

**Comment by cursiveclojure** [comment]
Ok, great - lein 2.5.1 seemed to cause all sorts of problems. I'll close this for now, then, and use your reproduction case for testing before trying the next lein version.
