### ISSUE TITLE
NullPointerException when I try to edit Clojure code style

### ISSUE THREAD

**Issue by arathunku** [cursiveclojure/cursive#795]
Exception details:
```
null
java.lang.NullPointerException
	at clojure.core$name.invoke(core.clj:1520)
	at cursive.language$with_language.invoke(language.clj:58)
	at cursive.extensions.clojure.core.resolve$global_var_meta.invoke(resolve.clj:136)
	at cursive.index$with_parsed.invoke(index.clj:402)
	at cursive.extensions.clojure.core.resolve$fn__5822.invoke(resolve.clj:514)
	at cursive.resolve.light$update_state$fn__1852.invoke(light.clj:124)
	at clojure.core.protocols$fn__6444.invoke(protocols.clj:84)
	at clojure.core.protocols$fn__6401$G__6396__6414.invoke(protocols.clj:13)
	at clojure.core$reduce.invoke(core.clj:6514)
	at cursive.resolve.light$update_state.invoke(light.clj:118)
	at cursive.resolve.light$process_top_level_lists.invoke(light.clj:191)
	at cursive.resolve.light$resolve_states$fn__1885.invoke(light.clj:218)
	at cursive.psi$cached_value$reify__1279.compute(psi.clj:447)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at cursive.psi$cached_value.doInvoke(psi.clj:450)
	at clojure.lang.RestFn.invoke(RestFn.java:445)
	at cursive.resolve.light$resolve_states.invoke(light.clj:218)
	at cursive.index$process_file.invoke(index.clj:35)
	at cursive.index$index_with.invoke(index.clj:72)
	at cursive.index$index_with.invoke(index.clj:64)
	at cursive.index$file_namespaces.invoke(index.clj:226)
	at clojure.lang.Var.invoke(Var.java:379)
	at cursive.psi.impl.ClojureFileImpl$NamespacesProvider.compute(ClojureFileImpl.java:134)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:200)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:83)
	at cursive.psi.impl.ClojureFileImpl.getAllNamespaces(ClojureFileImpl.java:148)
	at cursive.psi.ClojurePsiElements.getNs(ClojurePsiElements.java:40)
	at cursive.psi.ClojurePsiElementImpl.getNs(ClojurePsiElementImpl.java:29)
	at cursive.psi.ClojurePsiElementImpl.getInNs(ClojurePsiElementImpl.java:45)
	at cursive.psi$containing_ns.invoke(psi.clj:119)
	at cursive.symbol$var_meta.invoke(symbol.clj:41)
	at cursive.resolve.symbol$resolve_symbol.invoke(symbol.clj:84)
	at clojure.lang.Var.invoke(Var.java:383)
	at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:67)
	at cursive.psi.impl.symbols.SymbolReference$SymbolResolver.resolve(SymbolReference.java:64)
	at com.intellij.psi.impl.source.resolve.ResolveCache.a(ResolveCache.java:139)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:167)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:159)
	at cursive.psi.impl.symbols.SymbolReference.multiResolve(SymbolReference.java:58)
	at cursive.resolve$resolve.invoke(resolve.clj:52)
	at cursive.resolve$resolve_keys.invoke(resolve.clj:191)
	at cursive.formatting$list_block_params.invoke(formatting.clj:213)
	at cursive.formatting$basic_block_params.invoke(formatting.clj:294)
	at cursive.formatting$sub_blocks.invoke(formatting.clj:304)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$memoize$fn__5467.doInvoke(core.clj:6079)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at cursive.formatting.ElementBlock.getSubBlocks(formatting.clj:33)
	at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:177)
	at com.intellij.formatting.InitialInfoBuilder.a(InitialInfoBuilder.java:236)
	at com.intellij.formatting.InitialInfoBuilder.iteration(InitialInfoBuilder.java:110)
	at com.intellij.formatting.FormatProcessor$WrapBlocksState.doIteration(FormatProcessor.java:1335)
	at com.intellij.formatting.FormatProcessor$State.iteration(FormatProcessor.java:1268)
	at com.intellij.formatting.FormatProcessor.iteration(FormatProcessor.java:266)
	at com.intellij.formatting.FormatterImpl$MyFormattingTask.iteration(FormatterImpl.java:917)
	at com.intellij.formatting.FormatterImpl.a(FormatterImpl.java:308)
	at com.intellij.formatting.FormatterImpl.format(FormatterImpl.java:258)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.a(CodeFormatterFacade.java:131)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processRange(CodeFormatterFacade.java:95)
	at com.intellij.psi.impl.source.codeStyle.CodeFormatterFacade.processElement(CodeFormatterFacade.java:91)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:103)
	at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.reformat(CodeStyleManagerImpl.java:90)
	at com.intellij.application.options.CodeStyleAbstractPanel.b(CodeStyleAbstractPanel.java:270)
	at com.intellij.application.options.CodeStyleAbstractPanel.access$100(CodeStyleAbstractPanel.java:66)
	at com.intellij.application.options.CodeStyleAbstractPanel$3.run(CodeStyleAbstractPanel.java:214)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:937)
	at com.intellij.application.options.CodeStyleAbstractPanel.a(CodeStyleAbstractPanel.java:209)
	at com.intellij.application.options.CodeStyleAbstractPanel.access$000(CodeStyleAbstractPanel.java:66)
	at com.intellij.application.options.CodeStyleAbstractPanel$2.run(CodeStyleAbstractPanel.java:192)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:85)
	at com.intellij.application.options.CodeStyleAbstractPanel.b(CodeStyleAbstractPanel.java:189)
	at com.intellij.application.options.CodeStyleAbstractPanel.access$1100(CodeStyleAbstractPanel.java:66)
	at com.intellij.application.options.CodeStyleAbstractPanel$6.run(CodeStyleAbstractPanel.java:513)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:205)
	at java.awt.Dialog$1.run(Dialog.java:1049)
	at java.awt.Dialog$3.run(Dialog.java:1101)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Dialog.show(Dialog.java:1099)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog.show(DialogWrapperPeerImpl.java:782)
	at com.intellij.openapi.ui.impl.DialogWrapperPeerImpl.show(DialogWrapperPeerImpl.java:467)
	at com.intellij.openapi.ui.DialogWrapper.invokeShow(DialogWrapper.java:1614)
	at com.intellij.openapi.ui.DialogWrapper.show(DialogWrapper.java:1571)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:114)
	at com.intellij.ide.MacOSApplicationProvider$Worker$1.handlePreferences(MacOSApplicationProvider.java:99)
	at com.apple.eawt._AppEventLegacyHandler$2.dispatchEvent(_AppEventLegacyHandler.java:90)
	at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:168)
	at com.apple.eawt._AppEventLegacyHandler.handlePreferences(_AppEventLegacyHandler.java:88)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:253)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:244)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:489)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

I've got also problem when I try to create new file, maybe that's related 
![image](https://cloud.githubusercontent.com/assets/749393/6653868/968fffdc-caa1-11e4-9c6d-7c61e6aff183.png)

Newest IDEA 14.1, newest Cursive, fresh installation on OS X 10.9

**Comment by cursiveclojure** [comment]
There's something very strange going on there. I can't reproduce either of these. The new namespace issue is almost certainly related to the issue in the video you sent via twitter - for some reason your Clojure files don't have the right file type. Things to check:
1. Is the plugin correctly installed? Does it appear in Settings->Plugins? It's not in red in that view?
2. Do you have La Clojure installed, even if it's disabled?

**Comment by arathunku** [comment]
I've only one plugin for Clojure installed:
![image](https://cloud.githubusercontent.com/assets/749393/6654074/9505910c-caad-11e4-8ed7-7353a2211dfe.png)


Can I do anything for more details? I've reinstalled IDEA and Cursive already but problem still persists. I'm not sure if it's a Cursive or IDEA bug... :/

**Comment by arathunku** [comment]
Twitter discussion link for reference: https://twitter.com/arathunku/status/576869482964119552

**Comment by arathunku** [comment]
Pattern for `*.clj` had been missing.

![image](https://cloud.githubusercontent.com/assets/749393/6654115/8f3f5094-caaf-11e4-8e84-20691b2acaae.png)


All problems disappeared after I've specified that.
