### ISSUE TITLE
"Read access is allowed from event dispatch thread or inside read-action only" when loading file in REPL.

### ISSUE THREAD

**Issue by romstad** [cursiveclojure/cursive#810]
I'm having an annoying problem when using Cursive in the recently released InteliJ 14.1. Whenever I try to load a file in the REPL (by choosing "Tools"->"REPL"->"Load file in REPL" from the menu or pressing the equivalent key binding), I get the following error:

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[pool-7-thread-2,5,main] 732874252
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-1 14.1#IC-141.177.4, eap:false,6,main] 1513655412
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:982)
	at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.getDocument(FileDocumentManagerImpl.java:169)
	at cursive.repl.actions$do_load_file_BANG_.invoke(actions.clj:257)
	at cursive.repl.actions$load_files_BANG_.invoke(actions.clj:305)
	at cursive.repl.actions$load_file_BANG_.invoke(actions.clj:338)
	at cursive.repl.actions$load_file$fn__8605.invoke(actions.clj:384)
	at cursive.repl.nrepl$submit$fn__3548.invoke(nrepl.clj:69)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
```

I am running Cursive 0.1.50, IntelliJ 14.1, and OS X Yosemite. The error disappears when downgrading to IntelliJ 14.0.

**Comment by cursiveclojure** [comment]
Yes, sorry - this is fixed for the next drop, out in a day or two.
