### ISSUE TITLE
Cursive 0.1.53 / 0.1.54 Failed in IntelliJ 13.1

### ISSUE THREAD

**Issue by goldfrapp04** [cursiveclojure/cursive#844]
I had Cursive 0.1.4X and it worked fine. Earlier today I exited my IntelliJ, and when I restarted it, it threw an exception saying my Cursive is outdated and will be disabled. This was weird enough. 

Then I uninstalled this 0.1.4X and followed the official steps to install the latest version. Installation was successful, but when I restarted IntelliJ, this stack trace popped up:

> Plugin 'com.cursiveclojure.cursive' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.
> Caused by: java.lang.ClassNotFoundException: com.intellij.util.net.ssl.CertificateManager PluginClassLoader[com.cursiveclojure.cursive, 0.1.54]
>     at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:68)
>     at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
>     ... 44 more

I uninstalled the latest 0.1.54 and tried manually installing 0.1.53. The same thing happened.

**Comment by pecheny** [comment]
Seems that Idea is too outdated. I had the same issue with 13.1.2 but have found that CertificateManager class was introduced later. So last 13x release (13.1.6) works well for me.
