### ISSUE TITLE
Extract variable is broken in 0.1.54, IntelliJ 14.0

### ISSUE THREAD

**Issue by lucascs** [cursiveclojure/cursive#857]
Extract variable simply stopped working for me, a couple of versions ago, even inside a simple defn.

I hit the shortcut or the menu and nothing happens.

**Comment by cursiveclojure** [comment]
That's weird, I just tried this and it works for me. Do you get any errors in your log?

**Comment by lucascs** [comment]
I've got a bunch cyclic dependency errors, mostly on midje tests, and they usually mean nothing, pointing to midje internal namespaces.

Extract variable started working again, but there are some cases where it does nothing, I'll try to reproduce and isolate the case when it happens again.

**Comment by lucascs** [comment]
I could reproduce the issue:

```clj
(defn something []
  (for [account (db-acc/all-accounts (ddb/db))]
    {...}))
```

I want to extract `(ddb/db)` to a variable. So if I put the cursor right before the `(` it works fine. If I select `(ddb/db)` it does nothing. If I'm not wrong it used to work before.

**Comment by cursiveclojure** [comment]
Interesting - I'll try to reproduce this. In the case where it doesn't work, do you get an error in your log?

**Comment by lucascs** [comment]
Not on the event log.

**Comment by cursiveclojure** [comment]
I mean in the application log (*Help&rarr;Show log in Finder/Explorer*)

**Comment by lucascs** [comment]
```
2015-04-28 22:33:11,769 [428618074]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.IndexOutOfBoundsException
	at clojure.lang.RT.nthFrom(RT.java:843)
	at clojure.lang.RT.nth(RT.java:812)
	at cursive.refactoring.introduce$introduce_variable$fn__13328.invoke(introduce.clj:131)
	at cursive.refactoring.introduce.proxy$com.intellij.openapi.command.WriteCommandAction$ff19274a.run(Unknown Source)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:38)
	at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:114)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:977)
	at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
	at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
	at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
	at cursive.refactoring.introduce.proxy$com.intellij.openapi.command.WriteCommandAction$ff19274a.execute(Unknown Source)
	at cursive.refactoring.introduce$introduce_variable.invoke(introduce.clj:93)
	at cursive.refactoring.introduce$choose_scope.invoke(introduce.clj:162)
	at cursive.refactoring.introduce$find_occurrences$fn__13374.invoke(introduce.clj:187)
	at cursive.refactoring.introduce.proxy$com.intellij.openapi.util.Pass$ff19274a.pass(Unknown Source)
	at com.intellij.refactoring.introduce.inplace.OccurrencesChooser.showChooser(OccurrencesChooser.java:81)
	at cursive.refactoring.introduce$find_occurrences.invoke(introduce.clj:182)
	at cursive.refactoring.introduce$invoke$fn__13378.invoke(introduce.clj:200)
	at cursive.refactoring.introduce.proxy$com.intellij.openapi.util.Pass$ff19274a.pass(Unknown Source)
	at com.intellij.refactoring.IntroduceTargetChooser$4.run(IntroduceTargetChooser.java:121)
	at com.intellij.ui.popup.AbstractPopup$18.run(AbstractPopup.java:1343)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:651)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.g(FocusManagerImpl.java:632)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.e(FocusManagerImpl.java:602)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.access$200(FocusManagerImpl.java:60)
	at com.intellij.openapi.wm.impl.FocusManagerImpl$IdleRunnable.runEdt(FocusManagerImpl.java:108)
	at com.intellij.openapi.util.EdtRunnable$1.run(EdtRunnable.java:28)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)

```

**Comment by paplorinc** [comment]
+1, the content is just deleted, replaced with the given name (tried it wil latest 14 EAP)
