### ISSUE TITLE
Cursive fails with errors on invalid ~/.lein/profile.clj

### ISSUE THREAD

**Issue by prasincs** [cursiveclojure/cursive#868]
I'm submitting this because it was not at all clear for a long time why cursive was failing to load any projects or figure out project definition when importing a project. I did find the culprit -- it was my misconfigured `~/.lein/profiles.clj`, submitting this with the corresponding symptoms so that it can be made clearer in future releases.

```
{:ignore {:plugins [[cider/cider-nrepl "0.8.1"]
		  [lein-try "0.4.3"]
                  [jonase/eastwood "0.2.1"]
		  [lein-cloverage "1.0.2"]
                  ]
        :dependencies [[spyscope "0.1.5"]
                       [org.clojure/tools.namespace "0.2.9"]
                       [leiningen #=(leiningen.core.main/leiningen-version)]
                        [io.aviso/pretty "0.1.16"]
                        [im.chit/vinyasa "0.3.0"]]
        :injections [(require 'spyscope.core)
                     (require '[vinyasa.inject :as inject])
                     (require 'io.aviso.repl)
                     (inject/in ;; the default injected namespace is `.`

                      ;; note that `:refer, :all and :exclude can be used
                      [vinyasa.inject :refer [inject [in inject-in]]]
                      [vinyasa.lein :exclude [*project*]]

                      ;; imports all functions in vinyasa.pull
                      [vinyasa.pull :all]

                      ;; same as [cemerick.pomegranate
                      ;;           :refer [add-classpath get-classpath resources]]
                      [cemerick.pomegranate add-classpath get-classpath resources]

                      ;; inject into clojure.core
                      clojure.core
                      [vinyasa.reflection .> .? .* .% .%> .& .>ns .>var]

                      ;; inject into clojure.core with prefix
                      clojure.core >
                      [clojure.pprint pprint]
                      [clojure.java.shell sh])
                     ]}
 :uberjar {:aot :all}
}
```
As you can see I used to have a complicated `:dev` profile that was messing things up for another project.. I disabled it and default `:dev` profile was used there. However, when I upgraded Cursive - there were following errors:

* When I try to change an imported project to a leiningen project from context menu
```
No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:567)
	at clojure.java.io$fn__9072$G__9054__9079.invoke(io.clj:69)
	at clojure.java.io$reader.doInvoke(io.clj:102)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at leiningen.core.main$leiningen_version.invoke(main.clj:313)
	at clojure.lang.Var.invoke(Var.java:375)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1053)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:616)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1073)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1073)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1081)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1138)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1081)
	at clojure.lang.LispReader.read(LispReader.java:183)
	at clojure.lang.RT.readString(RT.java:1785)
	at clojure.core$read_string.invoke(core.clj:3648)
	at leiningen.core.utils$read_file.invoke(utils.clj:30)
	at leiningen.core.user$fn__10368.invoke(user.clj:67)
	at clojure.lang.AFn.applyToHelper(AFn.java:154)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$memoize$fn__5467.doInvoke(core.clj:6079)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at leiningen.core.user$fn__10371.invoke(user.clj:85)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$memoize$fn__5467.doInvoke(core.clj:6079)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at leiningen.core.project$read_profiles.invoke(project.clj:654)
	at leiningen.core.project$project_with_profiles.invoke(project.clj:798)
	at cursive.leiningen$read_project.invoke(leiningen.clj:78)
	at cursive.leiningen$load_project.invoke(leiningen.clj:86)
	at clojure.lang.Var.invoke(Var.java:379)
	at cursive.leiningen.utils.Interop.loadProject(Interop.java:22)
	at cursive.leiningen.project.LeiningenProject.reload(LeiningenProject.java:38)
	at cursive.leiningen.project.LeiningenProject.<init>(LeiningenProject.java:34)
	at cursive.leiningen.project.LeiningenProject.create(LeiningenProject.java:29)
	at cursive.leiningen.project.LeiningenProjectsManager.importLeiningenProjects(LeiningenProjectsManager.java:112)
	at cursive.leiningen.navigator.AddManagedFileAction.actionPerformed(AddManagedFileAction.java:22)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter$1.run(ActionMenuItem.java:312)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:958)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:124)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:282)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2018)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:109)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:512)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:44)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:532)
	at java.awt.Component.processMouseEvent(Component.java:6516)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at java.awt.Component.processEvent(Component.java:6281)
	at java.awt.Container.processEvent(Container.java:2229)
	at java.awt.Component.dispatchEventImpl(Component.java:4872)
	at java.awt.Container.dispatchEventImpl(Container.java:2287)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4832)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4492)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4422)
	at java.awt.Container.dispatchEventImpl(Container.java:2273)
	at java.awt.Window.dispatchEventImpl(Window.java:2719)
	at java.awt.Component.dispatchEvent(Component.java:4698)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:740)
	at java.awt.EventQueue.access$300(EventQueue.java:103)
	at java.awt.EventQueue$3.run(EventQueue.java:699)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.awt.EventQueue$4.run(EventQueue.java:713)
	at java.awt.EventQueue$4.run(EventQueue.java:711)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:710)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

* When I try to import a project using leiningen model, nothing would display on the list of projects.

I wasn't able to recreate it after re-instating the profiles.clj after Cursive did indeed work. Maybe going through reinstalling would recreate it, or it was just a random fluke on my machine. Submitting in case someone else has same issues.

**Comment by cursiveclojure** [comment]
Hmm, the problem there is the `#=(leiningen.core.main/leiningen-version)`, although to be honest I'm not sure why that's an issue. It's almost certainly some artefact of the fact that Cursive runs lein in-process, so the JDK is different and the classpath is sometimes subtly different too.

**Comment by prasincs** [comment]
I noticed I got the same error when I only had the following in my `~/.lein/profiles.clj` file 
`{: dev {:plugins [[cider/cider-nrepl "0.8.2"]]}}`

I was able to reproduce it quite accurately by removing the file and trying to import a new project. The projects wouldn't be listed in the UI if the nrepl dependency is in the `~/.lein/profiles.clj` file.

**Comment by cursiveclojure** [comment]
There's a space in there between the `:` and the `dev`, so that won't be read as the correct keyword. Is that the case in your actual project too? I still can't see why this would be the case, though. I'll try to take a look at this soon.

**Comment by bfabry** [comment]
I get the same issue with this profiles.clj, if I blank it out then importing projects works again
```
{:user {:plugins [[lein-cljsbuild "1.0.0"]
                  [lein-clojars "0.9.1"]
                  [lein-midje    "3.1.3"]
                  [lein-midje-doc "0.0.18"]
                  [cider/cider-nrepl "0.8.2"]]
   :dependencies [[org.clojure/tools.nrepl "0.2.7"]
                  [debugger "0.1.4"]
                  [spyscope "0.1.4"]
                  [org.clojure/tools.namespace "0.2.4"]
                  [leiningen #=(leiningen.core.main/leiningen-version)]
                  [im.chit/iroh "0.1.11"]
                  [io.aviso/pretty "0.1.12"]
                  [im.chit/vinyasa "0.2.2"]]
        :repl-options {
                       :nrepl-middleware [io.aviso.nrepl/pretty-middleware]
                       }
   :injections
   [(require 'spyscope.core)
    (require '[vinyasa.inject :as inject])]}}
```
