### ISSUE TITLE
stackoverflow error while synchronizing lein project

### ISSUE THREAD

**Issue by colinyip** [cursiveclojure/cursive#935]
version: 0.1.55
intelj: 14.1.4

stackoverflow error while synchronizing lein project in intellj.

error stack:
```java
null
java.lang.StackOverflowError
	at clojure.lang.RT.boundedLength(RT.java:1735)
	at clojure.lang.AFn.applyToHelper(AFn.java:148)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$update_in.doInvoke(core.clj:5919)
	at clojure.lang.RestFn.invoke(RestFn.java:467)
	at pedantic.core$transform_graph$fn__10482.invoke(core.clj:78)
	at clojure.core.protocols$fn__5251.invoke(protocols.clj:148)
	at clojure.core.protocols$fn__5208$G__5203__5217.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__5232.invoke(protocols.clj:75)
	at clojure.core.protocols$fn__5182$G__5177__5195.invoke(protocols.clj:13)
	at clojure.core.protocols$fn__5246.invoke(protocols.clj:122)
	at clojure.core.protocols$fn__5208$G__5203__5217.invoke(protocols.clj:19)
	at clojure.core.protocols$seq_reduce.invoke(protocols.clj:31)
	at clojure.core.protocols$fn__5232.invoke(protocols.clj:75)
.......
```

**Comment by cursiveclojure** [comment]
See #928 for a workaround and a dev build that fixes the problem. I'll be doing a full release hopefully today.

**Comment by colinyip** [comment]
awesome! thanks
