### ISSUE TITLE
Support for hierarchical projects (with lein-sub plugin)

### ISSUE THREAD

**Issue by jitlogic** [cursiveclojure/cursive#952]
This is feature request. The lein-sub plugin allows for creation of maven-like hierarchical projects. For example ring is organized this way: https://github.com/ring-clojure/ring

Cursive cannot open this project correctly. No subprojects nor source roots are recognized.

**Comment by danielcompton** [comment]
@jitlogic have you looked at setting up a project like https://cursiveclojure.com/userguide/leiningen.html ? See the part on "Working with multi-module projects". lein-sub seems to be designed to allow you to run lein commands against multiple sub projects, I don't think you'd need native Cursive support for it to be able to open the ring-clojure project.

**Comment by danielcompton** [comment]
I had the occasion to open a project using lein-sub, and found that I had to close and reopen the project after running Import Modules to get it to show up. I'm not sure if this is a Cursive or IntelliJ bug, but it wasn't very intuitive.

**Comment by cursiveclojure** [comment]
Yes, I'm working on a large re-work of how the lein integration works which should fix this amongst many other problems.

**Comment by hlship** [comment]
This is something that's affecting me as well, at my new job.  An existing code base, singe Git root, lots of sub-modules in sub-folders, all interdependent.

Ok, I never noticed the "search for sub-projects" option. Cool.

Not as cool:

```
10:20:17 AM Throwable
            Too many events posted
            java.lang.Throwable
            at com.intellij.openapi.diagnostic.FrequentEventDetector.eventHappened(FrequentEventDetector.java:61)
            at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.a(RefreshQueueImpl.java:97)
            at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.execute(RefreshQueueImpl.java:66)
            at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.launch(RefreshSessionImpl.java:104)
            at com.intellij.openapi.vfs.newvfs.RefreshQueue.refresh(RefreshQueue.java:58)
            at com.intellij.openapi.vfs.newvfs.RefreshQueue.refresh(RefreshQueue.java:44)
            at com.intellij.openapi.vfs.newvfs.NewVirtualFile.refresh(NewVirtualFile.java:85)
            at com.intellij.openapi.vfs.VirtualFile.refresh(VirtualFile.java:682)
            at cursive.leiningen.project.wizard.LeiningenProjectImportStep$2.visitFile(LeiningenProjectImportStep.java:111)
            at com.intellij.openapi.vfs.VirtualFileVisitor.visitFileEx(VirtualFileVisitor.java:132)
            at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.jav... (show balloon)
10:20:18 AM StackOverflowError: null
```

**Comment by hlship** [comment]
Here's more from idea.log:

```
2015-09-30 10:27:50,869 [  12145]  ERROR - plication.impl.ApplicationImpl - null
java.lang.StackOverflowError
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getName(VirtualFileSystemEntry.java:94)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl$FsRoot.appendPathOnFileSystem(PersistentFSImpl.java:1356)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.appendPathOnFileSystem(FileNameCache.java:122)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:166)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.appendPathOnFileSystem(FileNameCache.java:122)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:166)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.appendPathOnFileSystem(FileNameCache.java:122)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:166)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.appendPathOnFileSystem(FileNameCache.java:122)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:166)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.appendPathOnFileSystem(FileNameCache.java:122)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:166)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.appendPathOnFileSystem(FileNameCache.java:122)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:166)
	at com.intellij.openapi.vfs.newvfs.impl.FileNameCache.appendPathOnFileSystem(FileNameCache.java:122)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:166)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getPath(VirtualFileSystemEntry.java:190)
	at cursive.leiningen.project.LeiningenProject.hashCode(LeiningenProject.java:87)
	at java.util.HashMap.hash(HashMap.java:338)
	at java.util.HashMap.get(HashMap.java:556)
	at cursive.leiningen.project.LeiningenProjectsManager.combineDependencies(LeiningenProjectsManager.java:383)
	at cursive.leiningen.project.LeiningenProjectsManager.combineDependencies(LeiningenProjectsManager.java:387)
	at cursive.leiningen.project.LeiningenProjectsManager.combineDependencies(LeiningenProjectsManager.java:387)
	at cursive.leiningen.project.LeiningenProjectsManager.combineDependencies(LeiningenProjectsManager.java:387)
	at cursive.leiningen.project.LeiningenProjectsManager.combineDependencies(LeiningenProjectsManager.java:387)
```

**Comment by hlship** [comment]
<img width="1400" alt="ereceipts-services_-____workspaces_walmart_ereceipts-services_" src="https://cloud.githubusercontent.com/assets/52660/10200995/834b313a-675e-11e5-8c1a-921c46a05fc3.png">

This is what it looks like ... a long list of projects in the Leiningen window, but no modules listed in the explorer (or in the modules tab of the project settings).

**Comment by cursiveclojure** [comment]
I'm actually working on a large change to the lein support right now, which will hopefully fix all this. @hlship I'll let you know as soon as I have a dev build to test.

**Comment by cursiveclojure** [comment]
Actually, looking at `lein-sub`, it doesn't actually modify the dependency process at all. Cursive *should* be able to handle this already, I think. @hlship I'll take a look at those errors to see if I can figure out what's going on there.

**Comment by cursiveclojure** [comment]
@hlship can you send me a whole log showing that error?

**Comment by hlship** [comment]
I've had to send them out-of-band, by email.  Oh, I just should have renamed them to .txt.  Too late.

**Comment by cursiveclojure** [comment]
That's ok, email is probably better anyway. I'll take a look this morning.

**Comment by hlship** [comment]
I realized that there were some odd hacks in our project to try and make it work in Cursive; they're hacking enough that I would not blame Cursive for not handling them and I'm trying to back them out.

For comparison, I checked out Ring and tried to import it, getting several odd behaviors:

An exception:

```
java.lang.reflect.InvocationTargetException
java.lang.Error: java.lang.reflect.InvocationTargetException
	at com.intellij.openapi.application.WriteAction.execute(WriteAction.java:68)
	at cursive.leiningen.module.ModuleCreationUtils.importModule(ModuleCreationUtils.java:714)
	at cursive.leiningen.project.LeiningenProjectsManager$3.run(LeiningenProjectsManager.java:291)
	at cursive.leiningen.LeiningenUtil$4$1.run(LeiningenUtil.java:101)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
Caused by: java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1319)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1294)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1348)
	at com.intellij.openapi.application.WriteAction.execute(WriteAction.java:59)
	... 17 more
Caused by: java.lang.RuntimeException: com.intellij.util.io.MappingFailedException: Cannot map buffer
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.b(FSRecords.java:501)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.access$000(FSRecords.java:138)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.findRootRecord(FSRecords.java:774)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findRoot(PersistentFSImpl.java:876)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findRoot(PersistentFSImpl.java:56)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.a(VfsImplUtil.java:160)
	at com.intellij.openapi.vfs.newvfs.VfsImplUtil.findFileByPath(VfsImplUtil.java:60)
	at com.intellij.openapi.vfs.impl.jar.JarFileSystemImpl.findFileByPath(JarFileSystemImpl.java:125)
	at com.intellij.openapi.vfs.impl.VirtualFileManagerImpl.findFileByUrl(VirtualFileManagerImpl.java:135)
	at com.intellij.openapi.vfs.impl.FilePointerPartNode.update(FilePointerPartNode.java:262)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerImpl.getUrl(VirtualFilePointerImpl.java:69)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.clone(VirtualFilePointerContainerImpl.java:297)
	at com.intellij.openapi.vfs.impl.VirtualFilePointerContainerImpl.clone(VirtualFilePointerContainerImpl.java:288)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.c(LibraryImpl.java:612)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.b(LibraryImpl.java:600)
	at com.intellij.openapi.roots.impl.libraries.LibraryImpl.commit(LibraryImpl.java:582)
	at cursive.leiningen.module.ModuleCreationUtils$8.run(ModuleCreationUtils.java:696)
	at com.intellij.openapi.application.RunResult.run(RunResult.java:38)
	at com.intellij.openapi.application.WriteAction$1$1.run(WriteAction.java:47)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
	at com.intellij.openapi.application.WriteAction$1.run(WriteAction.java:44)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.util.io.MappingFailedException: Cannot map buffer
	at com.intellij.util.io.PagedFileStorage$StorageLock.createValue(PagedFileStorage.java:640)
	at com.intellij.util.io.PagedFileStorage$StorageLock.get(PagedFileStorage.java:559)
	at com.intellij.util.io.PagedFileStorage$StorageLock.access$500(PagedFileStorage.java:467)
	at com.intellij.util.io.PagedFileStorage.getBufferWrapper(PagedFileStorage.java:408)
	at com.intellij.util.io.PagedFileStorage.getBuffer(PagedFileStorage.java:372)
	at com.intellij.util.io.PagedFileStorage.put(PagedFileStorage.java:275)
	at com.intellij.util.io.ResizeableMappedFile.put(ResizeableMappedFile.java:221)
	at com.intellij.util.io.AppendableStorageBackedByResizableMappedFile.flushKeyStoreBuffer(AppendableStorageBackedByResizableMappedFile.java:47)
	at com.intellij.util.io.AppendableStorageBackedByResizableMappedFile.force(AppendableStorageBackedByResizableMappedFile.java:55)
	at com.intellij.util.io.PersistentEnumeratorBase.force(PersistentEnumeratorBase.java:549)
	at com.intellij.util.io.PersistentEnumeratorBase.markCorrupted(PersistentEnumeratorBase.java:596)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:294)
	at com.intellij.util.io.PersistentEnumeratorBase.enumerate(PersistentEnumeratorBase.java:309)
	at com.intellij.util.io.PersistentEnumeratorDelegate.enumerate(PersistentEnumeratorDelegate.java:75)
	at com.intellij.util.io.PersistentStringEnumerator.enumerate(PersistentStringEnumerator.java:70)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.findRootRecord(FSRecords.java:729)
	... 35 more
Caused by: java.io.FileNotFoundException: /Users/hship/Library/Caches/IntelliJIdea14/caches/names.dat.keystream (No such file or directory)
	at java.io.RandomAccessFile.open0(Native Method)
	at java.io.RandomAccessFile.open(RandomAccessFile.java:316)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:243)
	at com.intellij.util.io.ReadWriteDirectBufferWrapper$1.execute(ReadWriteDirectBufferWrapper.java:63)
	at com.intellij.util.io.ReadWriteDirectBufferWrapper$1.execute(ReadWriteDirectBufferWrapper.java:58)
	at com.intellij.openapi.util.io.FileUtilRt.doIOOperation(FileUtilRt.java:700)
	at com.intellij.util.io.ReadWriteDirectBufferWrapper.createFile(ReadWriteDirectBufferWrapper.java:58)
	at com.intellij.util.io.ReadWriteDirectBufferWrapper.create(ReadWriteDirectBufferWrapper.java:39)
	at com.intellij.util.io.DirectBufferWrapper.getBuffer(DirectBufferWrapper.java:47)
	at com.intellij.util.io.PagedFileStorage$StorageLock.createValue(PagedFileStorage.java:631)
	... 50 more
```

![ring_-____workspaces_github_ring_](https://cloud.githubusercontent.com/assets/52660/10252409/1e13d954-68ec-11e5-8329-0a6689847cbc.png)

**Comment by hlship** [comment]
The above seems to recur even after restarting IntelliJ (I did a clear caches and restart):

![ring_-____workspaces_github_ring_](https://cloud.githubusercontent.com/assets/52660/10252446/60f296b6-68ec-11e5-87a5-0f38982f1c2e.png)

**Comment by cursiveclojure** [comment]
So there's a mixed bag of issues here. The StackOverflowError issue is due to a dependency cycle in the projects, this is tracked in #1083. The "Too many events posted" error is due to an error in the way that Cursive walks directory trees when importing really large projects. I believe it is harmless, but is tracked in #1084. The other issues are quite low-level, and look to me like some sort of disk error. If they recur once the other issues are fixed please open a new issue.
