### ISSUE TITLE
NPE connecting to remote REPL

### ISSUE THREAD

**Issue by rauhs** [cursiveclojure/cursive#967]
I keep getting this NPE. I do have a NREPL  running and the `.nrepl-port` file exists. Not sure what is wrong. This worked just fine until now.

```
java.lang.NullPointerException
	at cursive.repl.remote_runner$find_lein_repl_port.invoke(remote_runner.clj:92)
	at cursive.repl.remote_runner$remote_config_factory$fn__21372$fn__21375$fn__21376.invoke(remote_runner.clj:119)
	at cursive.repl.remote_runner.proxy$java.lang.Object$RunProfileState$4749a946.execute(Unknown Source)
	at com.intellij.execution.runners.DefaultProgramRunner.doExecute(DefaultProgramRunner.java:33)
	at com.intellij.execution.runners.GenericProgramRunner$1.execute(GenericProgramRunner.java:43)
	at com.intellij.execution.RunProfileStarter.execute(RunProfileStarter.java:39)
	at com.intellij.execution.impl.ExecutionManagerImpl$3.run(ExecutionManagerImpl.java:219)
	at com.intellij.execution.impl.ExecutionManagerImpl.compileAndRun(ExecutionManagerImpl.java:134)
	at com.intellij.execution.impl.ExecutionManagerImpl.startRunProfile(ExecutionManagerImpl.java:259)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:40)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:64)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.runners.BaseProgramRunner.execute(BaseProgramRunner.java:53)
	at com.intellij.execution.runners.GenericProgramRunner.execute(GenericProgramRunner.java:31)
	at com.intellij.execution.ProgramRunnerUtil.executeConfiguration(ProgramRunnerUtil.java:94)
	at com.intellij.execution.impl.ExecutionManagerImpl.a(ExecutionManagerImpl.java:396)
	at com.intellij.execution.impl.ExecutionManagerImpl.access$400(ExecutionManagerImpl.java:61)
	at com.intellij.execution.impl.ExecutionManagerImpl$5.run(ExecutionManagerImpl.java:384)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
[  91815]  ERROR - til.concurrency.QueueProcessor - IntelliJ IDEA 14.1.4  Build #IU-141.1532.4 
[  91815]  ERROR - til.concurrency.QueueProcessor - JDK: 1.8.0_25 
[  91815]  ERROR - til.concurrency.QueueProcessor - VM: Java HotSpot(TM) 64-Bit Server VM 
[  91815]  ERROR - til.concurrency.QueueProcessor - Vendor: Oracle Corporation 
[  91815]  ERROR - til.concurrency.QueueProcessor - OS: Linux 
[  91815]  ERROR - til.concurrency.QueueProcessor - Last Action: Run 
```

**Comment by rauhs** [comment]
Issue seems to be related to not having a leiningen project.clj loaded (In case other people end up here in the future).
