### ISSUE TITLE
Error loading leiningen project.clj

### ISSUE THREAD

**Issue by rauhs** [cursiveclojure/cursive#968]
I'm getting an error trying to load my project.clj

Manually running `(leiningen.core.project/read-raw "project.clj")` works just fine for me however.

```
[  46929]  ERROR - ursive.leiningen.LeiningenUtil - Error loading /home/rauh/dev/srs-om/project.clj 
java.lang.Exception: Error loading /home/rauh/dev/srs-om/project.clj
	at leiningen.core.project$read_raw$fn__14193.invoke(project.clj:931)
	at leiningen.core.project$read_raw.invoke(project.clj:928)
	at cursive.leiningen$read_project.invoke(leiningen.clj:78)
	at cursive.leiningen$load_project.invoke(leiningen.clj:86)
	at clojure.lang.Var.invoke(Var.java:379)
	at cursive.leiningen.utils.Interop.loadProject(Interop.java:22)
	at cursive.leiningen.project.LeiningenProject.reload(LeiningenProject.java:38)
	at cursive.leiningen.project.LeiningenProject.<init>(LeiningenProject.java:34)
	at cursive.leiningen.project.LeiningenProject.create(LeiningenProject.java:29)
	at cursive.leiningen.project.LeiningenProjectsManager.importLeiningenProjects(LeiningenProjectsManager.java:114)
	at cursive.leiningen.navigator.AddManagedFilesAction.actionPerformed(AddManagedFilesAction.java:55)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:182)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:162)
	at com.intellij.openapi.actionSystem.impl.ActionButton.a(ActionButton.java:126)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:303)
	at java.awt.Component.processEvent(Component.java:6290)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4881)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4703)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil, compiling:(/home/rauh/dev/srs-om/project.clj:94:82)
	at clojure.lang.Compiler.load(Compiler.java:7353)
	at clojure.lang.Compiler.loadFile(Compiler.java:7284)
	at clojure.lang.RT$3.invoke(RT.java:319)
	at leiningen.core.project$read_raw$fn__14193.invoke(project.clj:929)
	... 46 more
Caused by: java.lang.IllegalArgumentException: No implementation of method: :make-reader of protocol: #'clojure.java.io/IOFactory found for class: nil
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:566)
	at clojure.java.io$fn__9115$G__9091__9122.invoke(io.clj:69)
	at clojure.java.io$reader.doInvoke(io.clj:102)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at leiningen.core.main$leiningen_version.invoke(main.clj:313)
	at clojure.lang.Var.invoke(Var.java:375)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1130)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1150)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1150)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.Compiler.load(Compiler.java:7340)
```

**Comment by cursiveclojure** [comment]
Are you able to share your `project.clj`? Does it do anything unusual, like load external files?

**Comment by rauhs** [comment]
Ah  I just figured out the problem:

`                             [leiningen #=(leiningen.core.main/leiningen-version)]`

is in my deps vector. Changing it to a version string works again. This also fixed #967 .

**Comment by udomatthias** [comment]
i have the same problem

C:\Users\priva\.lein\udo1>project.clj

C:\Users\priva\.lein\udo1>lein
java.lang.Exception: Error loading C:\Users\priva\.lein\udo1\project.clj
 at leiningen.core.project$read_raw$fn__3649.invoke (project.clj:1012)
    leiningen.core.project$read_raw.invokeStatic (project.clj:1006)
    leiningen.core.project$read_raw.invoke (project.clj:1002)
    leiningen.core.project$read.invokeStatic (project.clj:1023)
    leiningen.core.project$read.invoke (project.clj:1020)
    leiningen.core.project$read.invokeStatic (project.clj:1024)
    leiningen.core.project$read.invoke (project.clj:1020)
    leiningen.core.main$_main$fn__4734.invoke (main.clj:416)
    leiningen.core.main$_main.invokeStatic (main.clj:411)
    leiningen.core.main$_main.doInvoke (main.clj:408)
    clojure.lang.RestFn.invoke (RestFn.java:397)
    clojure.lang.Var.invoke (Var.java:375)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
Caused by: clojure.lang.Compiler$CompilerException: java.lang.IllegalArgumentException: No value supplied for key: [[org.clojure/clojure] [overtone]], compiling:(C:\Users\priva\.lein\udo1\project.clj:1:1)
 at clojure.lang.Compiler.load (Compiler.java:7391)
    clojure.lang.Compiler.loadFile (Compiler.java:7317)
    clojure.lang.RT$3.invoke (RT.java:320)
    leiningen.core.project$read_raw$fn__3649.invoke (project.clj:1010)
    leiningen.core.project$read_raw.invokeStatic (project.clj:1006)
    leiningen.core.project$read_raw.invoke (project.clj:1002)
    leiningen.core.project$read.invokeStatic (project.clj:1023)
    leiningen.core.project$read.invoke (project.clj:1020)
    leiningen.core.project$read.invokeStatic (project.clj:1024)
    leiningen.core.project$read.invoke (project.clj:1020)
    leiningen.core.main$_main$fn__4734.invoke (main.clj:416)
    leiningen.core.main$_main.invokeStatic (main.clj:411)
    leiningen.core.main$_main.doInvoke (main.clj:408)
    clojure.lang.RestFn.invoke (RestFn.java:397)
    clojure.lang.Var.invoke (Var.java:375)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)
Caused by: java.lang.IllegalArgumentException: No value supplied for key: [[org.clojure/clojure] [overtone]]
 at clojure.lang.PersistentHashMap.create (PersistentHashMap.java:77)
    clojure.core$hash_map.invokeStatic (core.clj:387)
    clojure.core$hash_map.doInvoke (core.clj:379)
    clojure.lang.RestFn.applyTo (RestFn.java:137)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.core$apply.invoke (core.clj:641)
    leiningen.core.project$argument_list__GT_argument_map.invokeStatic (project.clj:413)
    leiningen.core.project$argument_list__GT_argument_map.invoke (project.clj:408)
    leiningen.core.project$defproject.invokeStatic (project.clj:427)
    leiningen.core.project$defproject.doInvoke (project.clj:422)
    clojure.lang.RestFn.invoke (RestFn.java:497)
    clojure.lang.Var.invoke (Var.java:401)
    clojure.lang.AFn.applyToHelper (AFn.java:171)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.lang.Compiler.macroexpand1 (Compiler.java:6776)
    clojure.lang.Compiler.macroexpand (Compiler.java:6837)
    clojure.lang.Compiler.eval (Compiler.java:6911)
    clojure.lang.Compiler.load (Compiler.java:7379)
    clojure.lang.Compiler.loadFile (Compiler.java:7317)
    clojure.lang.RT$3.invoke (RT.java:320)
    leiningen.core.project$read_raw$fn__3649.invoke (project.clj:1010)
    leiningen.core.project$read_raw.invokeStatic (project.clj:1006)
    leiningen.core.project$read_raw.invoke (project.clj:1002)
    leiningen.core.project$read.invokeStatic (project.clj:1023)
    leiningen.core.project$read.invoke (project.clj:1020)
    leiningen.core.project$read.invokeStatic (project.clj:1024)
    leiningen.core.project$read.invoke (project.clj:1020)
    leiningen.core.main$_main$fn__4734.invoke (main.clj:416)
    leiningen.core.main$_main.invokeStatic (main.clj:411)
    leiningen.core.main$_main.doInvoke (main.clj:408)
    clojure.lang.RestFn.invoke (RestFn.java:397)
    clojure.lang.Var.invoke (Var.java:375)
    clojure.lang.AFn.applyToHelper (AFn.java:152)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.core$apply.invokeStatic (core.clj:646)
    clojure.main$main_opt.invokeStatic (main.clj:314)
    clojure.main$main_opt.invoke (main.clj:310)
    clojure.main$main.invokeStatic (main.clj:421)
    clojure.main$main.doInvoke (main.clj:384)
    clojure.lang.RestFn.invoke (RestFn.java:421)
    clojure.lang.Var.invoke (Var.java:383)
    clojure.lang.AFn.applyToHelper (AFn.java:156)
    clojure.lang.Var.applyTo (Var.java:700)
    clojure.main.main (main.java:37)

**Comment by udomatthias** [comment]
(defproject udo1 
  :dependencies [[org.clojure/clojure] 
		[overtone]])

**Comment by RomitGandhi07** [comment]
I have the same issue. This is my code.

(defproject task-api-two-endpoints "0.1.0-SNAPSHOT"
  :description "API with two endpoints."
  :url "https://github.com/RomitGandhi07/task-api-two-endpoints"
  :license {:name "EPL-2.0 OR GPL-2.0-or-later WITH Classpath-exception-2.0"
            :url "https://www.eclipse.org/legal/epl-2.0/"}

  :dependencies [[org.clojure/clojure "1.10.1"]
                 [ring/ring-core "2.0.0-alpha1"]]
           
  :main ^:skip-aot task-api-two-endpoints.core
  :target-path "target/%s"
  :profiles {:uberjar {:aot :all}})
